import JSZip from "jszip";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

const fileStem = "digital-economy-and-firm-innovation-final";
const paragraphs = [
  "Digital Economy and Firm Innovation",
  "Undergraduate Thesis - Final Manuscript",
  "",
  "Abstract",
  "This manuscript examines how digital transformation improves firm innovation through information efficiency and resource allocation.",
  "",
  "1. Introduction",
  "Digital technologies reshape the information environment of enterprises and provide new channels for innovation investment.",
  "",
  "2. Research Design",
  "The study uses firm-level panel data and tests the proposed mechanism with baseline and robustness regressions.",
  "",
  "3. Conclusion",
  "The results support the role of the digital economy in strengthening enterprise innovation capability.",
];

function download(blob: Blob, filename: string) {
  const href = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = href;
  anchor.download = filename;
  anchor.style.display = "none";
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(href), 1_000);
}

async function createPdf() {
  const document = await PDFDocument.create();
  const page = document.addPage([595.28, 841.89]);
  const font = await document.embedFont(StandardFonts.Helvetica);
  const bold = await document.embedFont(StandardFonts.HelveticaBold);
  page.drawText(paragraphs[0], { x: 56, y: 780, size: 20, font: bold, color: rgb(0.12, 0.18, 0.32) });
  page.drawText(paragraphs[1], { x: 56, y: 752, size: 11, font, color: rgb(0.35, 0.4, 0.48) });
  let y = 700;
  for (const paragraph of paragraphs.slice(3)) {
    if (!paragraph) { y -= 14; continue; }
    const heading = /^\d\. |Abstract$/.test(paragraph);
    page.drawText(paragraph, { x: 56, y, size: heading ? 13 : 10.5, font: heading ? bold : font, color: rgb(0.14, 0.18, 0.25), maxWidth: 480, lineHeight: 16 });
    y -= heading ? 26 : 34;
  }
  page.drawText("Generated by ThesisFlow", { x: 56, y: 42, size: 9, font, color: rgb(0.45, 0.5, 0.58) });
  return document.save();
}

async function createDocx() {
  const zip = new JSZip();
  zip.file("[Content_Types].xml", `<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>`);
  zip.folder("_rels")?.file(".rels", `<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`);
  const escaped = (value: string) => value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  const body = paragraphs.map((value, index) => `<w:p><w:r><w:rPr>${index === 0 ? "<w:b/><w:sz w:val=\"32\"/>" : ""}</w:rPr><w:t xml:space="preserve">${escaped(value || " ")}</w:t></w:r></w:p>`).join("");
  zip.folder("word")?.file("document.xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${body}<w:sectPr/></w:body></w:document>`);
  return zip.generateAsync({ type: "uint8array", compression: "DEFLATE" });
}

export async function exportFinalManuscript(type: "PDF" | "DOCX") {
  const bytes = type === "PDF" ? await createPdf() : await createDocx();
  download(new Blob([bytes], { type: type === "PDF" ? "application/pdf" : "application/vnd.openxmlformats-officedocument.wordprocessingml.document" }), `${fileStem}.${type.toLowerCase()}`);
}

export async function exportArchivePackage() {
  const [pdf, docx] = await Promise.all([createPdf(), createDocx()]);
  const zip = new JSZip();
  zip.file(`01_final-manuscript/${fileStem}.pdf`, pdf);
  zip.file(`01_final-manuscript/${fileStem}.docx`, docx);
  zip.file("README.txt", "ThesisFlow archive package\nIncludes the exported final manuscript in PDF and DOCX formats.\nMissing materials: plagiarism report; other attachments.\n");
  const blob = await zip.generateAsync({ type: "blob", compression: "DEFLATE" });
  download(blob, `${fileStem}-archive.zip`);
}

export function exportTextReport(filename: string, content: string) {
  download(new Blob([content], { type: "text/plain;charset=utf-8" }), filename);
}
