import { useState } from "react";
import { AlertTriangle, CheckCircle2, ChevronRight, ClipboardCheck, FileCheck2, FileWarning, Gauge, LockKeyhole, Send, ShieldAlert, Sparkles, Upload } from "lucide-react";
import "./final.css";

const finalChecks = ["结构", "逻辑", "引用", "文献", "数据", "一致性", "格式", "导师意见", "查重"];
const auditChecks = ["选题意义", "材料齐备", "文档规范", "写作安排", "逻辑构建", "专业能力", "学术规范"];
function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <section className={`final-card ${className}`}>{children}</section>; }
function Badge({ children, tone = "gray" }: { children: React.ReactNode; tone?: "green" | "amber" | "red" | "blue" | "gray" }) { return <span className={`final-badge ${tone}`}>{children}</span>; }
function PageTitle({ title, children }: { title: string; children?: React.ReactNode }) { return <header className="final-title"><div><p>定稿阶段 / 质量确认</p><h1>{title}</h1></div><div>{children}</div></header>; }

export function FinalizationPage() { const [issues, setIssues] = useState(["导师意见", "查重"]); const readiness = issues.length ? 94 : 100; return <section className="final-page"><PageTitle title="论文定稿"><Badge tone={issues.length ? "amber" : "green"}>Readiness {readiness}%</Badge><button className="final-primary" onClick={() => { if (issues.length) setIssues([]); }}> <FileCheck2 size={15} />生成定稿</button></PageTitle>{issues.length ? <div className="final-risk"><AlertTriangle size={16} /><div><b>生成定稿前仍有 {issues.length} 项重要问题</b><span>可先处理问题，或点击“生成定稿”以模拟带风险生成。</span></div><button onClick={() => setIssues([])}>模拟已处理</button></div> : <div className="final-ready"><CheckCircle2 size={16} />全部 Stage Gate 已满足，当前具备进入提交审核阶段的条件。</div>}<Card className="readiness-card"><div><p>论文定稿就绪度</p><strong>{readiness}<small>%</small></strong><span>{issues.length ? "建议先完成剩余关键检查" : "所有检查均已通过"}</span></div><i><em style={{ width: `${readiness}%` }} /></i><aside><b>{issues.length ? "下一步：处理重要问题" : "下一步：提交审核"}</b><span>{issues.length ? "导师意见与查重结果需确认" : "可生成定稿并准备提交材料"}</span></aside></Card><div className="final-check-grid">{finalChecks.map(item => { const issue = issues.includes(item); return <Card className={issue ? "needs-attention" : ""} key={item}>{issue ? <AlertTriangle size={18} /> : <CheckCircle2 size={18} />}<div><b>{item}</b><span>{issue ? "需处理" : "已满足"}</span></div><button onClick={() => setIssues(all => all.includes(item) ? all.filter(value => value !== item) : [...all, item])}>{issue ? "处理" : "查看"}<ChevronRight size={13} /></button></Card>; })}</div><Card className="final-next"><div><Sparkles size={17} /><p><b>定稿前建议</b><span>生成定稿会冻结当前版本，并保留一份可恢复的版本记录。</span></p></div><button className="final-secondary">查看定稿清单</button></Card></section>; }

export function PlagiarismPage() { const [uploaded, setUploaded] = useState(false); return <section className="final-page"><PageTitle title="查重记录"><Badge tone="amber">进入下一阶段：待确认</Badge><button className="final-primary" onClick={() => setUploaded(true)}><Upload size={15} />上传学校查重报告</button></PageTitle><div className="official-notice"><ShieldAlert size={17} /><div><b>校外辅助分析结果不等同于学校正式查重结果</b><span>以下为 Mock 历史记录与辅助分析预览，仅供修改前自查；请以学校正式报告为准。</span></div></div><div className="similarity-dashboard"><Card className="similarity-main"><span>总文字复制比</span><strong>23.7<small>%</small></strong><Badge tone="amber">历史 Mock 结果</Badge><p>记录时间：2026-04-08 · 校外辅助分析</p></Card>{[["AIGC 特征", "18.6%", "需关注"], ["高风险段落", "3", "待处理"], ["章节最高重复率", "31.4%", "第 2 章"]].map(([label, value, status]) => <Card className="similarity-small" key={label}><span>{label}</span><b>{value}</b><Badge tone="amber">{status}</Badge></Card>)}</div><div className="plagiarism-layout"><Card className="chapter-rate"><header><div><h2>章节重复率</h2><span>辅助分析 Mock</span></div><Badge tone="amber">第 2 章偏高</Badge></header>{[["第 1 章 绪论", 12.6], ["第 2 章 文献综述", 31.4], ["第 3 章 理论分析", 19.8], ["第 4 章 实证分析", 9.2], ["第 5 章 结论与建议", 7.5]].map(([chapter, rate]) => <div className="rate-row" key={String(chapter)}><span>{chapter}</span><i><em style={{ width: `${Number(rate) * 2.6}%` }} /></i><b>{rate}%</b></div>)}</Card><Card className="history-card"><header><h2>历史记录</h2><button>查看全部</button></header>{[["2026-04-08", "23.7%", "辅助分析"], ["2026-03-19", "26.1%", "辅助分析"], ["2026-02-22", "29.4%", "初稿自检"]].map(row => <div key={row[0]}><span>{row[0]}</span><b>{row[1]}</b><Badge tone="gray">{row[2]}</Badge></div>)}</Card></div><Card className="risk-paragraphs"><header><div><h2>高风险段落</h2><span>建议优先改写或补充规范引用</span></div><Badge tone="red">3 处</Badge></header>{[["第 2.2 节", "数字化转型的概念界定与既有文献表述相似度较高。", "31.4%"], ["第 3.1 节", "理论机制部分需要增加个人分析与引用标记。", "27.8%"], ["第 4.3 节", "稳健性检验的文字说明与公开表述重合。", "25.6%"]].map(row => <article key={row[0]}><FileWarning size={16} /><div><b>{row[0]}</b><p>{row[1]}</p></div><Badge tone="red">{row[2]}</Badge><button>定位 <ChevronRight size={13} /></button></article>)}</Card>{uploaded && <div className="upload-placeholder"><CheckCircle2 size={15} />学校查重报告已标记为“待解析”（交互占位，不上传真实文件）。</div>}</section>; }

const scoringRows = [["选题与研究价值", 25, 22], ["研究能力与方法", 25, 21], ["写作与论证质量", 25, 22], ["学术规范与态度", 25, 23]];
export function TeacherReviewPage() { const [agree, setAgree] = useState(false); return <section className="final-page"><PageTitle title="教师评阅"><Badge tone="blue">评分预演 / Mock</Badge></PageTitle><div className="review-disclaimer"><ClipboardCheck size={17} /><p><b>本页仅作评阅预演与学生自检记录，不代表真实教师评分或学校审核结论。</b><span>模拟数据依据学校评分结构展示，实际成绩和答辩资格以教师与学院的正式通知为准。</span></p></div><div className="teacher-layout"><div><Card className="score-sheet"><header><div><h2>指导教师评分（模拟）</h2><span>四项各 25 分</span></div><strong>88<small>/100</small></strong></header><table><thead><tr><th>评分项目</th><th>分值</th><th>模拟得分</th><th>观察意见</th></tr></thead><tbody>{scoringRows.map((row, index) => <tr key={row[0]}><td>{row[0]}</td><td>{row[1]}</td><td><b>{row[2]}</b></td><td>{index === 1 ? "建议补强内生性方案" : "符合当前阶段预期"}</td></tr>)}</tbody></table><footer><b>模拟意见：</b>论文选题具有现实意义，研究框架较完整；建议在答辩前进一步说明变量构造与稳健性检验。</footer></Card><Card className="score-sheet reviewer-sheet"><header><div><h2>评阅教师评分（模拟）</h2><span>四项各 25 分</span></div><strong>85<small>/100</small></strong></header><table><thead><tr><th>评分项目</th><th>分值</th><th>模拟得分</th><th>观察意见</th></tr></thead><tbody>{scoringRows.map((row, index) => <tr key={row[0]}><td>{row[0]}</td><td>{row[1]}</td><td><b>{[21, 20, 22, 22][index]}</b></td><td>{index === 0 ? "研究空白需进一步聚焦" : "符合当前阶段预期"}</td></tr>)}</tbody></table><footer><b>模拟意见：</b>整体达到预演要求，建议补充文献述评与样本筛选过程的说明。</footer></Card></div><aside><Card className="defense-score"><h2>答辩评分结构</h2><div><span>论文质量</span><b>25 分</b></div><div><span>答辩表现</span><b>25 分</b></div><div><span>问题回答</span><b>50 分</b></div><footer><strong>模拟总分</strong><b>86 / 100</b></footer></Card><Card className="defense-opinion"><h2>是否同意答辩</h2><p>当前仅作为预演记录。请完成查重确认和导师意见处理后再判断正式资格。</p><button className={agree ? "agree" : ""} onClick={() => setAgree(value => !value)}>{agree ? <CheckCircle2 size={15} /> : <Send size={15} />}{agree ? "模拟：同意答辩" : "记录模拟结论"}</button></Card><Card className="qualification"><LockKeyhole size={15} /><p><b>进入答辩准备的条件</b><span>需获得教师正式同意，并完成学院规定的查重与材料审核。</span></p></Card></aside></div></section>; }

export function SamplingPage() { const [fixed, setFixed] = useState<string[]>([]); const remaining = auditChecks.filter(item => !fixed.includes(item) && ["文档规范", "逻辑构建"].includes(item)); const level = remaining.length ? "中风险" : "低风险"; return <section className="final-page"><PageTitle title="论文抽检"><Badge tone={remaining.length ? "amber" : "green"}>抽检风险：{level}</Badge></PageTitle><div className="sampling-gate"><div><Gauge size={19} /><p><b>{remaining.length ? "尚不建议进入抽检提交" : "具备进入抽检提交的条件"}</b><span>{remaining.length ? `仍有 ${remaining.length} 项待修复，建议完成后再整理归档材料。` : "抽检清单已满足当前 Mock 规则。"}</span></p></div><button className="final-primary" disabled={remaining.length > 0}><Send size={15} />进入抽检提交</button></div><div className="audit-grid">{auditChecks.map((item, index) => { const issue = ["文档规范", "逻辑构建"].includes(item) && !fixed.includes(item); return <Card className={issue ? "audit-issue" : ""} key={item}>{issue ? <AlertTriangle size={18} /> : <CheckCircle2 size={18} />}<div><b>{item}</b><span>{issue ? index === 2 ? "目录页码需更新" : "章节衔接需补充" : "已通过"}</span></div><button onClick={() => issue && setFixed(list => [...list, item])}>{issue ? "修复" : "查看"}<ChevronRight size={13} /></button></Card>; })}</div><div className="sampling-bottom"><Card><h2>待修复项</h2>{remaining.length ? remaining.map(item => <p key={item}><AlertTriangle size={14} />{item}<button onClick={() => setFixed(list => [...list, item])}>标记修复</button></p>) : <p className="all-fixed"><CheckCircle2 size={14} />当前待修复项已清零</p>}</Card><Card><h2>抽检材料状态</h2><p><CheckCircle2 size={14} />论文正文与附件已关联</p><p><CheckCircle2 size={14} />导师指导记录已归档</p><p><AlertTriangle size={14} />学校正式查重报告待上传</p></Card></div></section>; }
