import type { DocumentBlock, NormalizedDocument, RuleCandidate, RuleCondition, SourceLocator } from "@/types/document";
const chinese:Record<string,number>={零:0,一:1,二:2,三:3,四:4,五:5,六:6,七:7,八:8,九:9,十:10,百:100,千:1000,万:10000};
export const parseChineseNumber=(raw:string)=>{if(/^\d+$/.test(raw))return Number(raw);let total=0,current=0;for(const c of raw){const n=chinese[c];if(n===undefined)return null;if(n>=10){current=current||1;total+=current*n;current=0}else current=n}return total+current};
const num=(text:string)=>{const m=text.match(/(\d+|[零一二三四五六七八九十百千万]+)/);return m?parseChineseNumber(m[1]):null};
const condition=(text:string):RuleCondition|null=>/藏族/.test(text)?{field:"student_group",operator:"equals",value:"tibetan"}:/普通学生/.test(text)?{field:"student_group",operator:"equals",value:"general"}:null;
const exception=(text:string):RuleCondition|null=>/不需|无需/.test(text)?{field:"translation_or_abstract",operator:"equals",value:"not_required"}:null;
const iso=(y:string,m:string,d:string)=>`${y}-${m.padStart(2,"0")}-${d.padStart(2,"0")}`;
export function extractDeadline(text:string){const range=text.match(/(20\d{2})\s*年\s*(\d{1,2})\s*月\s*(\d{1,2})\s*[-至]\s*(\d{1,2})\s*日/);if(range)return{value:{start:iso(range[1],range[2],range[3]),end:iso(range[1],range[2],range[4])},beforeOrOn:false};const single=text.match(/(20\d{2})\s*[年-]\s*(\d{1,2})\s*[月-]\s*(\d{1,2})\s*日?(前|前截止)?/);return single?{value:iso(single[1],single[2],single[3]),beforeOrOn:Boolean(single[4])}:null;}
const keyFor=(text:string)=>{if(/选题/.test(text))return"deadline.topic_confirm";if(/任务书/.test(text))return"deadline.taskbook";if(/开题/.test(text))return"deadline.proposal";if(/初稿/.test(text))return"deadline.first_draft";if(/中期/.test(text))return"deadline.midterm";if(/定稿/.test(text))return"deadline.final_draft";if(/答辩/.test(text))return"deadline.defense";if(/归档/.test(text))return"deadline.archive";return null};
export function extractRuleCandidates(document:NormalizedDocument):RuleCandidate[]{const out:RuleCandidate[]=[];document.blocks.forEach((block,index)=>{const text=block.text;const add=(ruleKey:string,value:unknown,unit:string|null,confidence=.9)=>out.push({id:`${document.documentId}:candidate:${index}:${out.length}`,projectId:"",projectFileId:document.projectFileId,documentParseId:document.documentId,ruleKey,category:ruleKey.split(".")[0],value,unit,rawText:text,locator:block.locator,confidence,extractor:"deterministic-v1",condition:condition(text),exception:exception(text),status:"pending",createdAt:"",updatedAt:""});const n=num(text);const deadline=extractDeadline(text);const deadlineKey=keyFor(text);if(deadline&&deadlineKey)add(deadlineKey,{...deadline,heading:block.type==="heading"?text:undefined},null,.95);if(n!==null){if(/正文.{0,8}(字|字符)/.test(text))add(/约|左右/.test(text)?"paper.body_words.target":"paper.body_words.min",/约|左右/.test(text)?{value:n,qualifier:"approximate"}:n,"words");if(/查重|复制比/.test(text))add("plagiarism.total.max_percent",n,"%");if(/AIGC/i.test(text))add("aigc.max_percent",n,"%");if(/指导.{0,6}(次|回)/.test(text))add("advisor.sessions.min",n,"sessions");if(/答辩.{0,8}(分钟|分)/.test(text)){const r=text.match(/(\d+)\s*[-至]\s*(\d+)/);if(r){add("defense.presentation_minutes.min",Number(r[1]),"minutes");add("defense.presentation_minutes.max",Number(r[2]),"minutes")}else add(/不超过|以内|不得超过/.test(text)?"defense.presentation_minutes.max":"defense.presentation_minutes.min",n,"minutes");}if(/文献/.test(text)&&/(篇|条)/.test(text))add(/外文/.test(text)?"references.foreign.min":/期刊/.test(text)?"references.journal.min":"references.total.min",n,"items");}if(/外文摘要/.test(text)&&/不需|无需/.test(text))add("abstract.en.content_words.approx",false,null,.95);});return out;}
export const candidatesConflict=(a:RuleCandidate,b:RuleCandidate)=>a.ruleKey===b.ruleKey&&JSON.stringify(a.condition)===JSON.stringify(b.condition)&&JSON.stringify(a.value)!==JSON.stringify(b.value);
