-- Phase 7 STEP 03-08: reproducible transforms, analysis runs and evidence lineage.
CREATE TABLE transform_recipes (id TEXT PRIMARY KEY NOT NULL, project_id TEXT NOT NULL, name TEXT NOT NULL, input_version_id TEXT NOT NULL, engine_version TEXT NOT NULL, recipe_hash TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY(project_id) REFERENCES thesis_projects(id) ON DELETE CASCADE, FOREIGN KEY(input_version_id) REFERENCES dataset_versions(id) ON DELETE RESTRICT);
CREATE TABLE transform_steps (id TEXT PRIMARY KEY NOT NULL, recipe_id TEXT NOT NULL, step_order INTEGER NOT NULL CHECK(step_order >= 0), operation TEXT NOT NULL, parameters_json TEXT NOT NULL, FOREIGN KEY(recipe_id) REFERENCES transform_recipes(id) ON DELETE CASCADE, UNIQUE(recipe_id, step_order));
CREATE TABLE transform_runs (id TEXT PRIMARY KEY NOT NULL, project_id TEXT NOT NULL, recipe_id TEXT NOT NULL, input_version_id TEXT NOT NULL, output_version_id TEXT, engine_version TEXT NOT NULL, input_hash TEXT NOT NULL, output_hash TEXT, status TEXT NOT NULL CHECK(status IN ('queued','running','completed','failed','cancelled')), logs_json TEXT NOT NULL DEFAULT '[]', error_message TEXT, created_at TEXT NOT NULL, completed_at TEXT, FOREIGN KEY(project_id) REFERENCES thesis_projects(id) ON DELETE CASCADE, FOREIGN KEY(recipe_id) REFERENCES transform_recipes(id) ON DELETE RESTRICT, FOREIGN KEY(input_version_id) REFERENCES dataset_versions(id) ON DELETE RESTRICT, FOREIGN KEY(output_version_id) REFERENCES dataset_versions(id) ON DELETE SET NULL);

CREATE TABLE variable_definitions (id TEXT PRIMARY KEY NOT NULL, project_id TEXT NOT NULL, code TEXT NOT NULL, display_name TEXT NOT NULL, dataset_version_id TEXT NOT NULL, column_name TEXT NOT NULL, role TEXT NOT NULL, conceptual_definition TEXT NOT NULL DEFAULT '', operational_definition TEXT NOT NULL DEFAULT '', unit TEXT NOT NULL DEFAULT '', expected_direction TEXT, transform_formula TEXT, provenance TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('confirmed','suggested','stale','broken')), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY(project_id) REFERENCES thesis_projects(id) ON DELETE CASCADE, FOREIGN KEY(dataset_version_id) REFERENCES dataset_versions(id) ON DELETE RESTRICT, UNIQUE(project_id, code));
CREATE INDEX idx_variable_definitions_project ON variable_definitions(project_id, status);

CREATE TABLE analysis_specs (id TEXT PRIMARY KEY NOT NULL, project_id TEXT NOT NULL, name TEXT NOT NULL, dataset_version_id TEXT NOT NULL, method TEXT NOT NULL, config_json TEXT NOT NULL, spec_hash TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('draft','validated','stale')), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY(project_id) REFERENCES thesis_projects(id) ON DELETE CASCADE, FOREIGN KEY(dataset_version_id) REFERENCES dataset_versions(id) ON DELETE RESTRICT);
CREATE TABLE analysis_runs (id TEXT PRIMARY KEY NOT NULL, project_id TEXT NOT NULL, spec_id TEXT NOT NULL, dataset_version_id TEXT NOT NULL, executor_id TEXT NOT NULL, executor_version TEXT NOT NULL, input_hash TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('queued','running','completed','failed','cancelled')), result_json TEXT, logs_json TEXT NOT NULL DEFAULT '[]', error_message TEXT, created_at TEXT NOT NULL, completed_at TEXT, FOREIGN KEY(project_id) REFERENCES thesis_projects(id) ON DELETE CASCADE, FOREIGN KEY(spec_id) REFERENCES analysis_specs(id) ON DELETE RESTRICT, FOREIGN KEY(dataset_version_id) REFERENCES dataset_versions(id) ON DELETE RESTRICT);
CREATE TABLE result_artifacts (id TEXT PRIMARY KEY NOT NULL, project_id TEXT NOT NULL, run_id TEXT NOT NULL, dataset_version_id TEXT NOT NULL, spec_id TEXT, artifact_type TEXT NOT NULL CHECK(artifact_type IN ('metric','table','chart','diagnostic')), structured_json TEXT NOT NULL, display_config_json TEXT NOT NULL DEFAULT '{}', content_hash TEXT NOT NULL, generator_version TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('ready','stale','archived')), created_at TEXT NOT NULL, FOREIGN KEY(project_id) REFERENCES thesis_projects(id) ON DELETE CASCADE, FOREIGN KEY(run_id) REFERENCES analysis_runs(id) ON DELETE RESTRICT, FOREIGN KEY(dataset_version_id) REFERENCES dataset_versions(id) ON DELETE RESTRICT, FOREIGN KEY(spec_id) REFERENCES analysis_specs(id) ON DELETE SET NULL);
CREATE TABLE evidence_blocks (id TEXT PRIMARY KEY NOT NULL, project_id TEXT NOT NULL, title TEXT NOT NULL, claim_scope TEXT NOT NULL, provenance_json TEXT NOT NULL, citation_label TEXT, stale INTEGER NOT NULL DEFAULT 0 CHECK(stale IN (0,1)), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY(project_id) REFERENCES thesis_projects(id) ON DELETE CASCADE);
CREATE TABLE evidence_block_links (evidence_block_id TEXT NOT NULL, artifact_id TEXT NOT NULL, metric_key TEXT, PRIMARY KEY(evidence_block_id, artifact_id, metric_key), FOREIGN KEY(evidence_block_id) REFERENCES evidence_blocks(id) ON DELETE CASCADE, FOREIGN KEY(artifact_id) REFERENCES result_artifacts(id) ON DELETE RESTRICT);
CREATE TABLE ai_explanations (id TEXT PRIMARY KEY NOT NULL, project_id TEXT NOT NULL, evidence_block_id TEXT NOT NULL, model TEXT NOT NULL, prompt_version TEXT NOT NULL, evidence_ids_json TEXT NOT NULL, sections_json TEXT NOT NULL, original_text TEXT NOT NULL, edited_text TEXT, status TEXT NOT NULL CHECK(status IN ('draft','stale','verified')), generated_at TEXT NOT NULL, FOREIGN KEY(project_id) REFERENCES thesis_projects(id) ON DELETE CASCADE, FOREIGN KEY(evidence_block_id) REFERENCES evidence_blocks(id) ON DELETE RESTRICT);

CREATE TRIGGER variable_version_scope BEFORE INSERT ON variable_definitions BEGIN SELECT CASE WHEN (SELECT project_id FROM dataset_versions WHERE id=NEW.dataset_version_id) != NEW.project_id THEN RAISE(ABORT, 'variable version must remain in project') END; END;
CREATE TRIGGER analysis_run_scope BEFORE INSERT ON analysis_runs BEGIN SELECT CASE WHEN (SELECT project_id FROM analysis_specs WHERE id=NEW.spec_id) != NEW.project_id OR (SELECT project_id FROM dataset_versions WHERE id=NEW.dataset_version_id) != NEW.project_id THEN RAISE(ABORT, 'analysis run must remain in project') END; END;
CREATE TRIGGER artifact_scope BEFORE INSERT ON result_artifacts BEGIN SELECT CASE WHEN (SELECT project_id FROM analysis_runs WHERE id=NEW.run_id) != NEW.project_id OR (SELECT project_id FROM dataset_versions WHERE id=NEW.dataset_version_id) != NEW.project_id THEN RAISE(ABORT, 'artifact must remain in project') END; END;
CREATE TRIGGER evidence_link_scope BEFORE INSERT ON evidence_block_links BEGIN SELECT CASE WHEN (SELECT project_id FROM evidence_blocks WHERE id=NEW.evidence_block_id) != (SELECT project_id FROM result_artifacts WHERE id=NEW.artifact_id) THEN RAISE(ABORT, 'evidence link must remain in project') END; END;
CREATE TRIGGER dataset_derived_marks_dependents_stale AFTER INSERT ON dataset_versions WHEN NEW.parent_version_id IS NOT NULL BEGIN
  UPDATE variable_definitions SET status='stale', updated_at=NEW.created_at WHERE dataset_version_id=NEW.parent_version_id;
  UPDATE result_artifacts SET status='stale' WHERE dataset_version_id=NEW.parent_version_id;
  UPDATE evidence_blocks SET stale=1, updated_at=NEW.created_at WHERE id IN (SELECT evidence_block_id FROM evidence_block_links WHERE artifact_id IN (SELECT id FROM result_artifacts WHERE dataset_version_id=NEW.parent_version_id));
  UPDATE ai_explanations SET status='stale' WHERE evidence_block_id IN (SELECT id FROM evidence_blocks WHERE stale=1);
END;
