import { describe, expect, it } from "vitest";
import { AITaskEngine, type AIRunOutput, type AIRunRepository, type AITaskInput } from "@/ai/taskEngine";
import { FakeProvider } from "@/ai/providerRegistry";
import type { AIRun } from "@/ai/domain";
const records = () => { const map = new Map<string, AIRun>(); const outputs: AIRunOutput[] = []; const repo: AIRunRepository = { create: async r => void map.set(r.id, r), update: async (id, c) => void map.set(id, { ...map.get(id)!, ...c }), get: async id => map.get(id) ?? null, listProject: async p => [...map.values()].filter(r => r.projectId === p), persistOutput: async o => void outputs.push(o), getOutput: async runId => outputs.find(output => output.aiRunId === runId) ?? null, appendStream: async () => {} }; return { repo, map, outputs }; };
const task = (projectId = "p") => ({ projectId, providerKey: "fake", modelId: "fake-text-v1", secretRef: "s", request: { task: { key: "generic", displayName: "generic", requiredCapabilities: ["text_generation"] as const }, modelId: "fake-text-v1", prompt: { key: "test", version: "1", role: "user" as const, enabled: true }, context: { items: [{ id: "x", kind: "user_input" as const, content: "x", trusted: true }], manifest: { itemIds: ["x"], totalCharacters: 1 } }, requestId: crypto.randomUUID() } });
describe("AI task engine", () => {
  it("persists a project-bound run and final usage/output", async () => { const x = records(); const engine = new AITaskEngine({ get: () => new FakeProvider() }, { resolve: async () => ({ secret: "never-in-ui" }) }, x.repo); const run = await engine.runAITask(task()); expect(run.status).toBe("succeeded"); expect(x.outputs).toHaveLength(1); expect((await engine.listProjectAIRuns("other"))).toEqual([]); });
  it("enforces project concurrency and rejects non-retryable auth errors", async () => { const x = records(); const provider = new FakeProvider(); provider.stream = async function* () { await new Promise(r => setTimeout(r, 20)); yield { type: "completed", response: { text: "ok" } }; }; const engine = new AITaskEngine({ get: () => provider }, { resolve: async () => ({ secret: "x" }) }, x.repo, { global: 1, perProject: 1, streamFlushMs: 1, defaultTimeoutMs: 100 }); const first = engine.runAITask(task()); await expect(engine.runAITask(task())).rejects.toThrow("queue"); await first; });
  it("persists timeout and cancellation as separate safe terminal states", async () => {
    const timeoutRecords = records(); const timeoutEngine = new AITaskEngine({ get: () => new FakeProvider("slow_stream") }, { resolve: async () => ({ secret: "x" }) }, timeoutRecords.repo, { global: 1, perProject: 1, streamFlushMs: 1, defaultTimeoutMs: 1 });
    await expect(timeoutEngine.runAITask(task())).resolves.toMatchObject({ status: "timed_out" });
    const cancelRecords = records(); const cancelEngine = new AITaskEngine({ get: () => new FakeProvider("slow_stream") }, { resolve: async () => ({ secret: "x" }) }, cancelRecords.repo, { global: 1, perProject: 1, streamFlushMs: 1, defaultTimeoutMs: 100 });
    const running = cancelEngine.runAITask(task()); await new Promise(resolve => setTimeout(resolve, 1)); const runId = [...cancelRecords.map.keys()][0]!; await cancelEngine.cancelAIRun(runId); await expect(running).resolves.toMatchObject({ status: "cancelled" });
  });
  it("blocks unsupported capabilities and persists invalid structured output without business writes", async () => {
    const x = records(); const engine = new AITaskEngine({ get: () => new FakeProvider("schema_invalid") }, { resolve: async () => ({ secret: "x" }) }, x.repo);
    const invalid = task() as AITaskInput; invalid.request = { ...invalid.request, structuredOutput: { key: "advisor_suggestions", version: "v1", jsonSchema: { type: "object" } } }; await expect(engine.runAITask(invalid)).resolves.toMatchObject({ status: "failed", error: { code: "schema_invalid" } }); expect(x.outputs[0]?.validationStatus).toBe("invalid");
    const unsupported = task() as AITaskInput; unsupported.request = { ...unsupported.request, task: { ...unsupported.request.task, requiredCapabilities: ["embeddings"] } }; await expect(engine.runAITask(unsupported)).rejects.toThrow("required task capability");
  });
});
