import { describe, expect, it, vi } from "vitest";
import { CrossrefProvider, OpenAlexProvider, buildMergePlan, parseBibTeX, parseRis, runBatchImport, similarityCandidate } from "@/services/literatureImportPipeline";

describe("literature import and metadata pipeline", () => {
  it("parses BibTeX and preserves source key/raw entry", () => { const [entry] = parseBibTeX("@article{smith2024, title={ A Study: }, author={Smith, Jane and Doe, John}, year={2024}, journal={Journal X}, doi={https://doi.org/10.1/ABC}, pages={1–12}}\n"); expect(entry).toMatchObject({ rawKey: "smith2024", title: "A Study", doi: "10.1/abc", venue: "Journal X", pages: "1-12" }); expect(entry.raw).toContain("smith2024"); });
  it("parses common RIS fields and retains raw record", () => { const [entry] = parseRis("TY  - JOUR\nTI  - Paper title\nAU  - Doe, Jane\nPY  - 2023/04/10\nJO  - Journal Y\nDO  - 10.2/xyz\nER  -\n"); expect(entry).toMatchObject({ title: "Paper title", year: 2023, venue: "Journal Y", doi: "10.2/xyz" }); expect(entry.raw).toContain("TY  - JOUR"); });
  it("never auto-merges a title-only near match", () => { expect(similarityCandidate({ title: "Shared title", authors: ["Doe, Jane"], year: 2024, raw: "", sourceType: "manual" }, { title: "Shared title", authors: ["Smith, John"], year: 2021, raw: "", sourceType: "manual" })).toBe("separate"); });
  it("uses mocked Crossref metadata with bounded provider response handling", async () => { const fetcher = vi.fn().mockResolvedValue({ ok: true, status: 200, json: async () => ({ message: { title: ["Remote work"], DOI: "10.3/ABC", published: { "date-parts": [[2022]] } } }) }); const result = await new CrossrefProvider("dev@example.test", fetcher).lookupDoi("doi:10.3/abc"); expect(result?.metadata).toMatchObject({ title: "Remote work", doi: "10.3/abc", year: 2022 }); expect(fetcher).toHaveBeenCalledTimes(1); });
  it("treats provider outage as an optional enrichment failure", async () => { const fetcher = vi.fn().mockResolvedValue({ ok: false, status: 503, json: async () => ({}) }); await expect(new OpenAlexProvider(undefined, fetcher).lookupDoi("10.4/outage")).resolves.toBeNull(); expect(fetcher).toHaveBeenCalledTimes(2); });
  it("preserves related records and creates an undo payload for a merge", () => { const plan = buildMergePlan("keep", "remove", { notes: ["n1"], tags: ["t1"], files: ["f1"], cards: [], provenance: ["p-user"] }, { notes: ["n2"], tags: ["t1"], files: ["f2"], cards: ["c2"], provenance: ["p-crossref"] }); expect(plan.merged).toEqual({ notes: ["n1","n2"], tags: ["t1"], files: ["f1","f2"], cards: ["c2"], provenance: ["p-user","p-crossref"] }); expect(plan.undoSnapshot.duplicate.notes).toEqual(["n2"]); });
  it("keeps processing a batch after a bad source", async () => { const result = await runBatchImport(["ok","bad","duplicate"], async item => { if (item === "bad") throw new Error("corrupt PDF"); return item === "duplicate" ? "duplicate" : "imported"; }); expect(result.map(x => x.status)).toEqual(["imported","retryable","duplicate"]); });
});
