import { describe, expect, it } from "vitest";
import { buildDefenseWorkspace, buildPracticeQuestions, buildSlideMaterials, createArchivePackage, createRecoveryReport, markDefenseStale, verifyArchivePackage } from "@/services/phase10Service";
import type { Phase10Inputs } from "@/types/phase10";

const inputs = { releaseCandidate: { id: "rc", projectId: "p1", documentId: "d1", label: "RC1", status: "candidate", ready: true, generatedAt: "2026-01-01", revisionId: "r1", revisionHash: "revision-hash", requirementsSnapshot: { version: "v", hash: "h", ids: [] }, citationSnapshot: { hash: "c", citationIds: [], literatureIds: [] }, evidenceSnapshot: { hash: "e", linkIds: [], staleIds: [] }, qaSummary: { openBlocking: 0, openFail: 0, review: 0, dismissed: 0, unsupported: 0, manualConfirmations: 0 }, exportManifest: null, manifestHash: "m", appVersion: "0.2.0", schemaVersion: "phase9-schema-1", checkerVersion: "phase9-checker-1.0.0", backup: { revision: {} as never, sections: [], citations: [], links: [] } }, sections: [{ id: "s1", documentId: "d1", projectId: "p1", parentId: null, sortOrder: 0, headingLevel: 1, title: "研究问题", content: "真实研究问题与结果。", contentFormat: "plain_text", wordCount: 10, purpose: "", targetLength: null, sourcePlan: [], createdAt: "", updatedAt: "" }], links: [], appVersion: "0.2.0" } as Phase10Inputs;

describe("Phase 10 domain services", () => {
  it("derives traceable student defense assets and marks RC changes stale", () => { const workspace = buildDefenseWorkspace(inputs); expect(workspace.cards[0].sources[0].id).toBe("s1"); expect(buildSlideMaterials(workspace)[0].sources).toHaveLength(1); expect(buildPracticeQuestions(inputs, workspace)[0].prompt).toContain("研究问题"); expect(markDefenseStale(workspace, "new-hash").stale).toBe(true); });
  it("creates, verifies, rejects traversal and reports recovery", async () => { const pkg = await createArchivePackage({ projectId: "p1", appVersion: "0.2.0", source: "final-rc", version: "rc1", files: [{ logicalId: "rc", relativePath: "final/rc.json", content: "{\"ok\":true}", type: "json" }] }); expect((await verifyArchivePackage(pkg)).valid).toBe(true); const report = await createRecoveryReport(pkg, "p1", "0014"); expect(report.status).toBe("completed"); await expect(createArchivePackage({ projectId: "p1", appVersion: "0.2.0", source: "x", version: "x", files: [{ logicalId: "x", relativePath: "../escape", content: "x", type: "text" }] })).rejects.toThrow("非法归档路径"); });
  it("rejects tampered archive contents", async () => { const pkg = await createArchivePackage({ projectId: "p1", appVersion: "0.2.0", source: "final-rc", version: "rc1", files: [{ logicalId: "rc", relativePath: "final/rc.json", content: "ok", type: "text" }] }); pkg.files["final/rc.json"] = "tampered"; expect((await verifyArchivePackage(pkg)).valid).toBe(false); });
});
