import { CheckCircle2, FileSpreadsheet, FileText, GraduationCap } from "lucide-react";
import { Radar, RadarChart, PolarGrid, PolarAngleAxis, ResponsiveContainer } from "recharts";
import { mockThesisProject as project } from "@/data/mock/thesis-project";

const ratio = (value: number, target: number) => Math.min(100, Math.round((value / target) * 100));
export function OverviewPage() { return <div className="overview-page">
  <section className="overview-hero"><div className="hero-icon"><GraduationCap size={52}/></div><div className="hero-meta"><h1>项目总览</h1><h2>{project.title}<span>本科毕业论文</span></h2><p>{project.school}　{project.college}　{project.major}　{project.cohort}</p><p>指导教师：{project.advisor}　　创建时间：{project.createdAt}</p></div><div className="hero-progress"><small>当前阶段</small><strong>{project.currentStage}</strong><div className="thin-progress"><i style={{width:`${project.completion}%`}}/></div><p>总体进度 <b>{project.completion}%</b></p></div></section>
  <section className="overview-card requirements"><header><h2>论文规范达成情况</h2><button>编辑规范</button></header><div className="requirement-grid">{project.requirements.map(item => <article className={`requirement ${item.tone}`} key={item.id}><div><small>{item.label}</small>{ratio(item.current,item.target)>=100 && <CheckCircle2 size={14}/>}</div><strong>{item.current}<em> / {item.target}{item.unit}</em></strong><div className="thin-progress"><i style={{width:`${ratio(item.current,item.target)}%`}}/></div><p>{ratio(item.current,item.target)}%</p></article>)}</div></section>
  <div className="overview-columns"><div className="overview-main"><section className="overview-card workflow" aria-label="19 阶段工作流"><header><h2>工作流程</h2><div className="workflow-legend"><span className="completed">已完成</span><span className="active">进行中</span><span>待开始</span><span className="overdue">已逾期</span></div></header><div className="workflow-grid">{project.workflow.map(stage => <article className={`workflow-stage ${stage.status}`} key={stage.id}><div className="workflow-dot">{String(stage.id).padStart(2,"0")}</div><strong>{stage.id.toString().padStart(2,"0")} {stage.title}</strong><small>{stage.date}</small></article>)}</div></section><div className="bottom-grid"><section className="overview-card compact"><header><h2>导师指导记录</h2><b>{project.metrics.advisorGuidance.current} / {project.metrics.advisorGuidance.target} 次</b></header>{project.guidanceRecords.map(row=><p className="list-row" key={row.index}><span>#{row.index}　{row.title}</span><small>{row.date}</small></p>)}<button className="outline-button">查看全部记录</button></section><section className="overview-card compact"><header><h2>待办任务</h2><b>{project.todos.length} 项</b></header>{project.todos.map(todo=><p className="list-row todo" key={todo.title}><span><i/> {todo.title}<em className={todo.priority}>{todo.priority}</em></span><small>截止：{todo.due}</small></p>)}<button className="outline-button">查看全部任务</button></section><section className="overview-card evaluation"><header><h2>AI论文智评 <small>（最新）</small></h2></header><div className="score"><strong>{project.evaluation.score}</strong><span>良好<br/><b>★★★★★</b></span></div><div className="radar"><ResponsiveContainer><RadarChart data={project.evaluation.dimensions}><PolarGrid/><PolarAngleAxis dataKey="subject" tick={{fontSize:10,fill:"#667085"}}/><Radar dataKey="score" stroke="#315efb" fill="#315efb" fillOpacity={.16}/></RadarChart></ResponsiveContainer></div><button className="outline-button">查看详细报告</button></section></div></div>
  <aside className="overview-rail"><section className="overview-card milestones" aria-label="近期节点"><h2>近期节点</h2>{project.milestones.map(item=><p className={item.status} key={item.date}><time>{item.date}</time><span>{item.title}</span><b>{item.detail}</b></p>)}</section><section className="overview-card calendar"><h2>日程日历</h2><strong>{project.calendar.label}</strong><div className="weekdays">{project.calendar.weekdays.map(day=><span key={day}>{day}</span>)}</div><div className="calendar-days">{project.calendar.days.map(day=><span className={day===project.calendar.highlightedDay?"selected":""} key={day}>{day}</span>)}</div></section><section className="overview-card compact files"><h2>文件动态</h2>{project.recentFiles.map(file=><p className="list-row" key={file.name}><span>{file.type === "sheet" ? <FileSpreadsheet size={15}/> : <FileText size={15}/>} {file.name}</span><small>{file.updatedAt}</small></p>)}<button className="outline-button">查看全部文件</button></section></aside></div>
</div>; }
