import type { DatasetVersion } from "@/types/dataset";

export type VariableRole = "dependent" | "independent" | "control" | "moderator" | "mediator" | "fixed-effect" | "id" | "time" | "other";
export interface VariableDefinition { id: string; projectId: string; code: string; displayName: string; datasetVersionId: string; column: string; role: VariableRole; conceptualDefinition: string; operationalDefinition: string; unit: string; expectedDirection: string | null; transformFormula: string | null; status: "confirmed" | "suggested" | "stale" | "broken"; provenance: string; }
export interface DescriptiveMetric { variable: string; n: number; missing: number; mean: number | null; sd: number | null; min: number | null; max: number | null; }
export interface AnalysisRun { id: string; projectId: string; datasetVersionId: string; spec: Record<string, unknown>; inputHash: string; status: "completed" | "failed"; metrics: Record<string, unknown>; logs: string[]; }
const mean = (values: number[]) => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : null;
export function descriptiveStatistics(version: DatasetVersion, rows: string[][]): DescriptiveMetric[] { return version.schema.map((column, index) => { const numbers = rows.map((row) => Number(row[index])).filter((value) => Number.isFinite(value)); const missing = rows.length - rows.filter((row) => row[index] !== "").length; const average = mean(numbers); const sd = average === null ? null : Math.sqrt(numbers.reduce((sum, value) => sum + (value - average) ** 2, 0) / Math.max(numbers.length - 1, 1)); return { variable: column.name, n: numbers.length, missing, mean: average, sd, min: numbers.length ? Math.min(...numbers) : null, max: numbers.length ? Math.max(...numbers) : null }; }); }
export function validateVariableMapping(variable: VariableDefinition, version: DatasetVersion): VariableDefinition { const column = version.schema.find((item) => item.name === variable.column); return { ...variable, status: variable.datasetVersionId !== version.id ? "stale" : column ? "confirmed" : "broken" }; }
export function validateAnalysisSpec(spec: Record<string, unknown>, version: DatasetVersion) { const dependent = typeof spec.dependent === "string" ? spec.dependent : ""; const independent = Array.isArray(spec.independent) ? spec.independent : []; const names = new Set(version.schema.map((column) => column.name)); if (!dependent || !names.has(dependent) || !independent.every((item) => typeof item === "string" && names.has(item))) throw new Error("分析规格引用了不存在的变量。"); return true; }
export function runDescriptiveAnalysis(projectId: string, version: DatasetVersion, rows: string[][], spec: Record<string, unknown>): AnalysisRun { const metrics = Object.fromEntries(descriptiveStatistics(version, rows).map((metric) => [metric.variable, metric])); return { id: crypto.randomUUID(), projectId, datasetVersionId: version.id, spec: { ...spec, method: "descriptive" }, inputHash: version.sha256, status: "completed", metrics, logs: [`descriptive: ${rows.length} rows`] }; }
