import { getDatabase } from "@/lib/database";
import { validateAnalysisSpec } from "@/services/analysisService";
import type { DatasetVersion } from "@/types/dataset";
import type { AnalysisRun, VariableDefinition } from "@/services/analysisService";
import type { EvidenceBlock } from "@/services/evidenceGuardrails";

const now = () => new Date().toISOString();
const id = () => crypto.randomUUID();
const hash = async (value: unknown) => Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(JSON.stringify(value))))).map((item) => item.toString(16).padStart(2, "0")).join("");

export class AnalysisPersistenceService {
  async listVariables(projectId: string): Promise<VariableDefinition[]> { const db = await getDatabase(); const rows = await db.select<Array<Record<string, unknown>>>("SELECT id,project_id AS projectId,code,display_name AS displayName,dataset_version_id AS datasetVersionId,column_name AS column,role,conceptual_definition AS conceptualDefinition,operational_definition AS operationalDefinition,unit,expected_direction AS expectedDirection,transform_formula AS transformFormula,provenance,status FROM variable_definitions WHERE project_id = ? ORDER BY code", [projectId]); return rows as unknown as VariableDefinition[]; }
  async saveVariable(variable: VariableDefinition) { const db = await getDatabase(); await db.execute("INSERT INTO variable_definitions (id,project_id,code,display_name,dataset_version_id,column_name,role,conceptual_definition,operational_definition,unit,expected_direction,transform_formula,provenance,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(project_id,code) DO UPDATE SET display_name=excluded.display_name,dataset_version_id=excluded.dataset_version_id,column_name=excluded.column_name,status=excluded.status,updated_at=excluded.updated_at", [variable.id, variable.projectId, variable.code, variable.displayName, variable.datasetVersionId, variable.column, variable.role, variable.conceptualDefinition, variable.operationalDefinition, variable.unit, variable.expectedDirection, variable.transformFormula, variable.provenance, variable.status, now(), now()]); return variable; }
  async createAnalysisSpec(projectId: string, name: string, version: DatasetVersion, method: string, config: Record<string, unknown>) { validateAnalysisSpec(config, version); const spec = { id: id(), projectId, name, datasetVersionId: version.id, method, config, specHash: await hash(config), status: "validated" as const, createdAt: now(), updatedAt: now() }; const db = await getDatabase(); await db.execute("INSERT INTO analysis_specs (id,project_id,name,dataset_version_id,method,config_json,spec_hash,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)", [spec.id, projectId, name, version.id, method, JSON.stringify(config), spec.specHash, spec.status, spec.createdAt, spec.updatedAt]); return spec; }
  async createRun(run: AnalysisRun, specId: string, executorId = "local-descriptive", executorVersion = "1.0.0") { const db = await getDatabase(); await db.execute("INSERT INTO analysis_runs (id,project_id,spec_id,dataset_version_id,executor_id,executor_version,input_hash,status,result_json,logs_json,created_at,completed_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)", [run.id, run.projectId, specId, run.datasetVersionId, executorId, executorVersion, run.inputHash, run.status === "completed" ? "completed" : "failed", JSON.stringify(run.metrics), JSON.stringify(run.logs), now(), now()]); return run; }
  async createArtifact(projectId: string, runId: string, datasetVersionId: string, type: "metric" | "table" | "chart" | "diagnostic", structured: Record<string, unknown>, specId?: string) { const db = await getDatabase(); const createdAt = now(); const contentHash = await hash(structured); const artifact = { id: id(), projectId, runId, datasetVersionId, artifactType: type, structured, contentHash, generatorVersion: "1.0.0", status: "ready", createdAt }; await db.execute("INSERT INTO result_artifacts (id,project_id,run_id,dataset_version_id,spec_id,artifact_type,structured_json,content_hash,generator_version,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)", [artifact.id, projectId, runId, datasetVersionId, specId ?? null, type, JSON.stringify(structured), contentHash, artifact.generatorVersion, artifact.status, createdAt]); return artifact; }
  async saveEvidence(evidence: EvidenceBlock, artifactIds: string[]) { const db = await getDatabase(); await db.execute("INSERT INTO evidence_blocks (id,project_id,title,claim_scope,provenance_json,stale,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)", [evidence.id, evidence.projectId, evidence.title, "analysis-result", JSON.stringify({ runId: evidence.runId, metrics: evidence.metrics }), evidence.stale ? 1 : 0, now(), now()]); for (const artifactId of artifactIds) await db.execute("INSERT INTO evidence_block_links (evidence_block_id,artifact_id,metric_key) VALUES (?,?,?)", [evidence.id, artifactId, null]); return evidence; }
  async saveExplanation(input: { id: string; projectId: string; evidenceBlockId: string; model: string; promptVersion: string; evidenceIds: string[]; sections: Record<string, string>; originalText: string; editedText?: string | null; }) { if (!input.evidenceIds.length) throw new Error("AI explanation 必须绑定 evidence。"); const db = await getDatabase(); const generatedAt = now(); await db.execute("INSERT INTO ai_explanations (id,project_id,evidence_block_id,model,prompt_version,evidence_ids_json,sections_json,original_text,edited_text,status,generated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)", [input.id, input.projectId, input.evidenceBlockId, input.model, input.promptVersion, JSON.stringify(input.evidenceIds), JSON.stringify(input.sections), input.originalText, input.editedText ?? null, "draft", generatedAt]); return { ...input, generatedAt, status: "draft" as const }; }
}

export const analysisPersistenceService = new AnalysisPersistenceService();
