import { normalizeIdentifier } from "@/services/literatureServices";

export type ImportedMetadata = { title?: string; authors?: string[]; year?: number | null; publicationDate?: string | null; venue?: string; volume?: string; issue?: string; pages?: string; publisher?: string; type?: string; doi?: string; url?: string; rawKey?: string; raw: string; sourceType: "bibtex" | "ris" | "pdf_metadata" | "manual" | "crossref" | "openalex" };
export type MetadataLookup = { provider: string; metadata: ImportedMetadata; raw: unknown; fetchedAt: string };
export interface ScholarlyMetadataProvider { readonly key: "crossref" | "openalex" | string; lookupDoi(doi: string, signal?: AbortSignal): Promise<MetadataLookup | null>; }
const clean = (value?: string | null) => value?.replace(/\s+/g, " ").trim() || undefined;
export const normalizeTitle = (value: string) => clean(value)?.replace(/[\s:;,.]+$/g, "") ?? "";
export const normalizeVenue = (value?: string) => clean(value)?.replace(/\s+/g, " ");
export const normalizePages = (value?: string) => clean(value)?.replace(/[–—]/g, "-").replace(/\s*-\s*/g, "-");
export const normalizeUrl = (value?: string) => { const v = clean(value); if (!v) return undefined; try { const url = new URL(v); url.hash = ""; return url.toString(); } catch { return v; } };
export const normalizeAuthor = (value: string) => clean(value)?.replace(/\s*,\s*/g, ", ") ?? "";
export function normalizeImportedMetadata(input: ImportedMetadata): ImportedMetadata { const date = clean(input.publicationDate); const parsedYear = input.year ?? (date && /^\d{4}/.test(date) ? Number(date.slice(0, 4)) : null); return { ...input, title: input.title ? normalizeTitle(input.title) : undefined, authors: input.authors?.map(normalizeAuthor).filter(Boolean), year: parsedYear, publicationDate: date, venue: normalizeVenue(input.venue), pages: normalizePages(input.pages), doi: input.doi ? normalizeIdentifier("doi", input.doi) : undefined, url: normalizeUrl(input.url) }; }
export function parseBibTeX(raw: string): ImportedMetadata[] { const entries: ImportedMetadata[] = []; for (const block of raw.matchAll(/@([\w-]+)\s*\{\s*([^,]+),([\s\S]*?)\}\s*(?=@|$)/g)) { const fields = Object.fromEntries([...block[3].matchAll(/(\w+)\s*=\s*[{"]([\s\S]*?)[}"]\s*,?/g)].map(m => [m[1].toLowerCase(), clean(m[2]) ?? ""])); entries.push(normalizeImportedMetadata({ title: fields.title, authors: fields.author?.split(/\s+and\s+/i), year: fields.year ? Number(fields.year) || null : null, venue: fields.journal || fields.booktitle, volume: fields.volume, issue: fields.number, pages: fields.pages, publisher: fields.publisher, doi: fields.doi, url: fields.url, type: block[1].toLowerCase(), rawKey: block[2].trim(), raw, sourceType: "bibtex" })); } return entries; }
export function parseRis(raw: string): ImportedMetadata[] { const groups = raw.split(/(?:^|\n)ER  -\s*(?:\n|$)/).filter(Boolean); return groups.map(record => { const f: Record<string,string[]> = {}; for (const line of record.split(/\r?\n/)) { const match = /^(\w\w)\s*-\s*(.*)$/.exec(line); if (match) (f[match[1]] ??= []).push(match[2]); } return normalizeImportedMetadata({ title: f.TI?.[0] || f.T1?.[0], authors: f.AU || f.A1, year: Number((f.PY?.[0] || f.Y1?.[0] || "").slice(0,4)) || null, publicationDate: f.PY?.[0] || f.Y1?.[0], venue: f.JO?.[0] || f.JF?.[0] || f.T2?.[0], volume: f.VL?.[0], issue: f.IS?.[0], pages: f.SP?.[0] && f.EP?.[0] ? `${f.SP[0]}-${f.EP[0]}` : f.SP?.[0], publisher: f.PB?.[0], doi: f.DO?.[0], url: f.UR?.[0], type: f.TY?.[0]?.toLowerCase(), raw, sourceType: "ris" }); }); }
export function pdfMetadataCandidate(metadata: Record<string, unknown>, firstPageText: string): ImportedMetadata { const title = typeof metadata.Title === "string" ? metadata.Title : firstPageText.split(/\r?\n/).find(line => line.trim().length > 8); const doi = firstPageText.match(/(?:doi\s*[:]?\s*|https?:\/\/(?:dx\.)?doi\.org\/)(10\.\d{4,9}\/[\w.()/:;-]+)/i)?.[1]; return normalizeImportedMetadata({ title, doi, raw: JSON.stringify({ metadata, firstPageText: firstPageText.slice(0, 4000) }), sourceType: "pdf_metadata" }); }
export function similarityCandidate(left: ImportedMetadata, right: ImportedMetadata): "strong" | "possible" | "separate" { if (left.doi && right.doi && left.doi === right.doi) return "strong"; const title = normalizeTitle(left.title ?? "").toLowerCase(); const other = normalizeTitle(right.title ?? "").toLowerCase(); const sameYear = !!left.year && left.year === right.year; const sameAuthor = !!left.authors?.[0] && !!right.authors?.[0] && normalizeAuthor(left.authors[0]).toLowerCase() === normalizeAuthor(right.authors[0]).toLowerCase(); if (title && title === other && sameYear && sameAuthor) return "strong"; if (title && title === other && (sameYear || sameAuthor)) return "possible"; return "separate"; }
export type MergeBundle<T = string> = { notes: T[]; tags: T[]; files: T[]; cards: T[]; provenance: T[] };
export type MergePlan<T = string> = { primaryId: string; duplicateId: string; merged: MergeBundle<T>; undoSnapshot: { primary: MergeBundle<T>; duplicate: MergeBundle<T> } };
const union = <T>(values: T[]) => [...new Set(values)];
/** A repository must persist this as one transaction; the snapshot is its explicit undo payload. */
export function buildMergePlan<T>(primaryId: string, duplicateId: string, primary: MergeBundle<T>, duplicate: MergeBundle<T>): MergePlan<T> { if (primaryId === duplicateId) throw new Error("Cannot merge a literature item into itself."); return { primaryId, duplicateId, merged: { notes: union([...primary.notes, ...duplicate.notes]), tags: union([...primary.tags, ...duplicate.tags]), files: union([...primary.files, ...duplicate.files]), cards: union([...primary.cards, ...duplicate.cards]), provenance: union([...primary.provenance, ...duplicate.provenance]) }, undoSnapshot: { primary, duplicate } }; }
export async function runBatchImport<T>(items: readonly T[], importOne: (item: T) => Promise<"imported" | "duplicate">): Promise<Array<{ item: T; status: "imported" | "duplicate" | "retryable"; error?: string }>> { const results: Array<{ item: T; status: "imported" | "duplicate" | "retryable"; error?: string }> = []; for (const item of items) { try { results.push({ item, status: await importOne(item) }); } catch (error) { results.push({ item, status: "retryable", error: error instanceof Error ? error.message : "Import failed" }); } } return results; }
async function request(url: string, init: RequestInit, fetcher: typeof fetch, signal?: AbortSignal) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 8_000); const linked = signal ? AbortSignal.any([signal, controller.signal]) : controller.signal; try { for (let attempt = 0; attempt < 2; attempt++) { const response = await fetcher(url, { ...init, signal: linked }); if ((response.status === 429 || response.status >= 500) && attempt === 0) { await new Promise(resolve => setTimeout(resolve, 250)); continue; } if (!response.ok) return null; return response.json() as Promise<unknown>; } return null; } finally { clearTimeout(timer); } }
export class CrossrefProvider implements ScholarlyMetadataProvider { readonly key = "crossref"; private cache = new Map<string, MetadataLookup | null>(); constructor(private readonly mailto: string | undefined, private readonly fetcher: typeof fetch = fetch) {} async lookupDoi(doi: string, signal?: AbortSignal) { const normalized = normalizeIdentifier("doi", doi); if (this.cache.has(normalized)) return this.cache.get(normalized)!; const query = this.mailto ? `?mailto=${encodeURIComponent(this.mailto)}` : ""; const raw = await request(`https://api.crossref.org/v1/works/${encodeURIComponent(normalized)}${query}`, { headers: { "User-Agent": "ThesisFlow/0.1 metadata-import" } }, this.fetcher, signal) as { message?: Record<string, unknown> } | null; const work = raw?.message; const result = work ? { provider: this.key, fetchedAt: new Date().toISOString(), raw, metadata: normalizeImportedMetadata({ title: Array.isArray(work.title) ? String(work.title[0] ?? "") : undefined, authors: Array.isArray(work.author) ? work.author.map(a => `${String((a as Record<string,unknown>).family ?? "")}, ${String((a as Record<string,unknown>).given ?? "")}`.replace(/^, |, $/g, "")) : [], year: Number((work.published as { "date-parts"?: number[][] } | undefined)?.["date-parts"]?.[0]?.[0]) || null, venue: Array.isArray(work["container-title"]) ? String(work["container-title"][0] ?? "") : undefined, volume: typeof work.volume === "string" ? work.volume : undefined, issue: typeof work.issue === "string" ? work.issue : undefined, pages: typeof work.page === "string" ? work.page : undefined, publisher: typeof work.publisher === "string" ? work.publisher : undefined, doi: typeof work.DOI === "string" ? work.DOI : normalized, type: typeof work.type === "string" ? work.type : undefined, raw: JSON.stringify(raw), sourceType: "crossref" }) } : null; this.cache.set(normalized, result); return result; } }
export class OpenAlexProvider implements ScholarlyMetadataProvider { readonly key = "openalex"; private cache = new Map<string, MetadataLookup | null>(); constructor(private readonly apiKey?: string, private readonly fetcher: typeof fetch = fetch) {} async lookupDoi(doi: string, signal?: AbortSignal) { const normalized = normalizeIdentifier("doi", doi); if (this.cache.has(normalized)) return this.cache.get(normalized)!; const key = this.apiKey ? `&api_key=${encodeURIComponent(this.apiKey)}` : ""; const raw = await request(`https://api.openalex.org/works/https://doi.org/${encodeURIComponent(normalized)}?${key.slice(1)}`, {}, this.fetcher, signal) as Record<string,unknown> | null; const result = raw ? { provider: this.key, fetchedAt: new Date().toISOString(), raw, metadata: normalizeImportedMetadata({ title: typeof raw.title === "string" ? raw.title : undefined, year: typeof raw.publication_year === "number" ? raw.publication_year : null, publicationDate: typeof raw.publication_date === "string" ? raw.publication_date : undefined, venue: ((raw.primary_location as Record<string,unknown> | undefined)?.source as Record<string,unknown> | undefined)?.display_name as string | undefined, doi: typeof raw.doi === "string" ? raw.doi : normalized, url: typeof raw.doi === "string" ? raw.doi : undefined, raw: JSON.stringify(raw), sourceType: "openalex" }) } : null; this.cache.set(normalized, result); return result; } }
