import type { DatasetColumn, DatasetColumnType } from "@/types/dataset";

export type TransformOperation = "select" | "rename" | "cast" | "fill_missing" | "filter" | "sort" | "dedupe" | "map" | "derive";
export interface TransformStep { operation: TransformOperation; parameters: Record<string, unknown>; }
export interface TransformInput { columns: DatasetColumn[]; rows: string[][]; }
export interface TransformOutput extends TransformInput { recipeHash: string; logs: string[]; }
const allowedTypes = new Set<DatasetColumnType>(["string", "number", "boolean", "date", "unknown"]);
const key = (row: string[], columns: DatasetColumn[], name: string) => row[columns.findIndex((column) => column.name === name)];
const hash = async (value: unknown) => Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(JSON.stringify(value))))).map((item) => item.toString(16).padStart(2, "0")).join("");

export async function executeTransform(input: TransformInput, steps: TransformStep[]): Promise<TransformOutput> {
  let columns = input.columns.map((column) => ({ ...column })); let rows = input.rows.map((row) => [...row]); const logs: string[] = [];
  for (const step of steps) {
    const p = step.parameters;
    if (step.operation === "select") { const names = Array.isArray(p.columns) ? p.columns.filter((value): value is string => typeof value === "string") : []; if (!names.length || names.some((name) => !columns.some((column) => column.name === name))) throw new Error("select 需要已存在的 columns。"); const indexes = names.map((name) => columns.findIndex((column) => column.name === name)); columns = names.map((name) => columns.find((column) => column.name === name)!); rows = rows.map((row) => indexes.map((index) => row[index])); }
    else if (step.operation === "rename") { const from = String(p.from ?? ""); const to = String(p.to ?? "").trim(); const index = columns.findIndex((column) => column.name === from); if (index < 0 || !to || columns.some((column, i) => i !== index && column.name === to)) throw new Error("rename 参数无效。"); columns[index] = { ...columns[index], name: to }; }
    else if (step.operation === "cast") { const name = String(p.column ?? ""); const type = String(p.type ?? "") as DatasetColumnType; const index = columns.findIndex((column) => column.name === name); if (index < 0 || !allowedTypes.has(type)) throw new Error("cast 参数无效。"); rows = rows.map((row) => { const value = row[index]; if (!value) return row; if (type === "number" && !Number.isFinite(Number(value))) throw new Error(`无法将 ${name} 转为 number。`); if (type === "boolean" && !/^(true|false)$/i.test(value)) throw new Error(`无法将 ${name} 转为 boolean。`); return row; }); columns[index] = { ...columns[index], type }; }
    else if (step.operation === "fill_missing") { const name = String(p.column ?? ""); const value = String(p.value ?? ""); const index = columns.findIndex((column) => column.name === name); if (index < 0) throw new Error("fill_missing 列不存在。"); rows = rows.map((row) => { const next = [...row]; if (!next[index]) next[index] = value; return next; }); columns[index] = { ...columns[index], nullable: false }; }
    else if (step.operation === "filter") { const name = String(p.column ?? ""); const operator = String(p.operator ?? "eq"); const expected = String(p.value ?? ""); if (!columns.some((column) => column.name === name)) throw new Error("filter 列不存在。"); rows = rows.filter((row) => { const actual = key(row, columns, name) ?? ""; if (operator === "eq") return actual === expected; if (operator === "neq") return actual !== expected; if (operator === "gt") return Number(actual) > Number(expected); if (operator === "gte") return Number(actual) >= Number(expected); if (operator === "lt") return Number(actual) < Number(expected); if (operator === "lte") return Number(actual) <= Number(expected); throw new Error("filter operator 不在 allowlist。"); }); }
    else if (step.operation === "sort") { const name = String(p.column ?? ""); const direction = p.direction === "desc" ? -1 : 1; const index = columns.findIndex((column) => column.name === name); if (index < 0) throw new Error("sort 列不存在。"); rows.sort((a, b) => a[index].localeCompare(b[index], undefined, { numeric: true }) * direction); }
    else if (step.operation === "dedupe") { const names = Array.isArray(p.columns) ? p.columns.filter((value): value is string => typeof value === "string") : columns.map((column) => column.name); const indexes = names.map((name) => columns.findIndex((column) => column.name === name)); if (indexes.some((index) => index < 0)) throw new Error("dedupe 列不存在。"); const seen = new Set<string>(); rows = rows.filter((row) => { const value = indexes.map((index) => row[index]).join("\u0001"); if (seen.has(value)) return false; seen.add(value); return true; }); }
    else if (step.operation === "map") { const name = String(p.column ?? ""); const values = p.values; const index = columns.findIndex((column) => column.name === name); if (index < 0 || !values || typeof values !== "object" || Array.isArray(values)) throw new Error("map 参数无效。"); rows = rows.map((row) => { const next = [...row]; const replacement = (values as Record<string, unknown>)[next[index]]; if (replacement !== undefined) next[index] = String(replacement); return next; }); }
    else if (step.operation === "derive") { const name = String(p.name ?? "").trim(); const formula = String(p.formula ?? ""); const match = /^([A-Za-z_][\w]*)\s*([+\-*/])\s*([A-Za-z_][\w]*)$/.exec(formula); if (!name || columns.some((column) => column.name === name) || !match || !columns.some((column) => column.name === match[1]) || !columns.some((column) => column.name === match[3])) throw new Error("derive 仅允许 column operator column 的安全表达式。"); const left = columns.findIndex((column) => column.name === match[1]); const right = columns.findIndex((column) => column.name === match[3]); rows = rows.map((row) => { const a = Number(row[left]); const b = Number(row[right]); if (![a, b].every(Number.isFinite)) throw new Error("derive 输入必须是数字。"); const value = match[2] === "+" ? a + b : match[2] === "-" ? a - b : match[2] === "*" ? a * b : b === 0 ? NaN : a / b; if (!Number.isFinite(value)) throw new Error("derive 产生了无效数值。"); return [...row, String(value)]; }); columns = [...columns, { name, sourceName: name, type: "number", nullable: false }]; }
    logs.push(`${step.operation}: ${rows.length} rows`);
  }
  return { columns, rows, logs, recipeHash: await hash({ columns, rows, steps }) };
}
