import { getDatabase } from "@/lib/database";
import JSZip from "jszip";
import type { EvidenceBlock } from "@/services/evidenceGuardrails";
import type { CitationAudit, ThesisAiProposal, ThesisCitation, ThesisDocument, ThesisExportManifest, ThesisRevision, ThesisSection, ThesisSourceLink, WritingSource, WritingWorkspace } from "@/types/writing";

const now = () => new Date().toISOString();
const id = () => crypto.randomUUID();
const desktop = () => typeof window !== "undefined" && "__TAURI_INTERNALS__" in window;
const storageKey = (projectId: string) => `thesisflow:writing:${projectId}`;
async function hash(value: unknown) { return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(JSON.stringify(value))))).map((x) => x.toString(16).padStart(2, "0")).join(""); }
const countWords = (value: string) => value.replace(/<[^>]+>/g, " ").trim().split(/\s+/u).filter(Boolean).length + (value.match(/[\u4e00-\u9fff]/gu)?.length ?? 0);

function emptyWorkspace(projectId: string, title: string): WritingWorkspace {
  const timestamp = now(); const documentId = id();
  return { document: { id: documentId, projectId, title, status: "draft", activeVersion: 0, metadata: {}, createdAt: timestamp, updatedAt: timestamp }, sections: [], revisions: [], citations: [], links: [], proposals: [] };
}

export class WritingService {
  async auditCitations(projectId: string): Promise<CitationAudit> { if (!desktop()) return { citationCount: 0, distinctLiteratureCount: 0, orphanCount: 0, duplicateAnchorCount: 0, staleCount: 0 }; const db = await getDatabase(); const rows = await db.select<{ citationCount: number; distinctLiteratureCount: number; orphanCount: number; staleCount: number }[]>("SELECT COUNT(*) AS citationCount,COUNT(DISTINCT literature_id) AS distinctLiteratureCount,SUM(CASE WHEN l.id IS NULL THEN 1 ELSE 0 END) AS orphanCount,SUM(CASE WHEN c.updated_at < l.updated_at THEN 1 ELSE 0 END) AS staleCount FROM thesis_citations c LEFT JOIN literature_items l ON l.id=c.literature_id WHERE c.project_id=?", [projectId]); const duplicates = await db.select<{ count: number }[]>("SELECT COUNT(*) AS count FROM (SELECT anchor FROM thesis_citations WHERE project_id=? GROUP BY anchor HAVING COUNT(*)>1)", [projectId]); return { citationCount: Number(rows[0]?.citationCount ?? 0), distinctLiteratureCount: Number(rows[0]?.distinctLiteratureCount ?? 0), orphanCount: Number(rows[0]?.orphanCount ?? 0), duplicateAnchorCount: Number(duplicates[0]?.count ?? 0), staleCount: Number(rows[0]?.staleCount ?? 0) }; }
  async listEvidence(projectId: string): Promise<EvidenceBlock[]> { if (!desktop()) return []; const db = await getDatabase(); const rows = await db.select<Record<string, unknown>[]>("SELECT e.id,e.project_id AS projectId,e.run_id AS runId,e.title,e.stale,e.provenance_json AS provenanceJson,COALESCE(GROUP_CONCAT(l.artifact_id), '') AS artifactIds FROM evidence_blocks e LEFT JOIN evidence_block_links l ON l.evidence_block_id=e.id WHERE e.project_id=? GROUP BY e.id ORDER BY e.updated_at DESC", [projectId]); return rows.map((row) => { const provenance = JSON.parse(String(row.provenanceJson ?? "{}")) as { metrics?: EvidenceBlock["metrics"] }; return { id: String(row.id), projectId: String(row.projectId), runId: String(row.runId ?? ""), title: String(row.title), stale: Boolean(row.stale), metrics: provenance.metrics ?? [], artifactIds: String(row.artifactIds ?? "").split(",").filter(Boolean) }; }); }
  async exportDocx(workspace: WritingWorkspace, bibliography: Array<{ title: string; authors: string; year: number | null }> = []): Promise<Blob> {
    const escapeXml = (value: string) => value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&apos;");
    const paragraphs = workspace.sections.flatMap((section) => [`<w:p><w:pPr><w:pStyle w:val="Heading${Math.min(section.headingLevel, 3)}"/></w:pPr><w:r><w:t>${escapeXml(section.title)}</w:t></w:r></w:p>`, ...section.content.replace(/<br\s*\/?>/gi, "\n").replace(/<[^>]+>/g, "").split(/\n+/u).filter(Boolean).map((text) => `<w:p><w:r><w:t xml:space="preserve">${escapeXml(text)}</w:t></w:r></w:p>`) ]);
    if (bibliography.length) paragraphs.push(`<w:p><w:pPr><w:pStyle w:val="Heading1"/></w:pPr><w:r><w:t>参考文献</w:t></w:r></w:p>`, ...bibliography.map((entry, index) => `<w:p><w:r><w:t>${index + 1}. ${escapeXml(entry.authors || "作者待补充")}（${entry.year ?? "n.d."}）. ${escapeXml(entry.title)}.</w:t></w:r></w:p>`));
    const sourceNotes = workspace.links.map((link) => `<w:p><w:r><w:t>${escapeXml(`[来源] ${link.label} · ${link.sourceType} · ${link.sourceId}${link.evidenceId ? ` · evidence=${link.evidenceId}` : ""}${link.artifactId ? ` · artifact=${link.artifactId}` : ""}${link.runId ? ` · run=${link.runId}` : ""}`)}</w:t></w:r></w:p>`);
    paragraphs.push(...sourceNotes);
    const documentXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${paragraphs.join("")}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr></w:body></w:document>`;
    const zip = new JSZip(); zip.file("[Content_Types].xml", `<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>`); zip.file("_rels/.rels", `<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`); zip.file("word/document.xml", documentXml); return zip.generateAsync({ type: "blob", mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document" });
  }
  async load(projectId: string, title: string): Promise<WritingWorkspace> {
    if (!desktop()) { const raw = localStorage.getItem(storageKey(projectId)); if (raw) return JSON.parse(raw) as WritingWorkspace; const fresh = emptyWorkspace(projectId, title); localStorage.setItem(storageKey(projectId), JSON.stringify(fresh)); return fresh; }
    const db = await getDatabase();
    const docs = await db.select<Record<string, unknown>[]>("SELECT id,project_id AS projectId,title,status,active_version AS activeVersion,metadata_json AS metadataJson,created_at AS createdAt,updated_at AS updatedAt FROM thesis_documents WHERE project_id=?", [projectId]);
    if (!docs[0]) { const fresh = emptyWorkspace(projectId, title); await db.execute("INSERT INTO thesis_documents (id,project_id,title,status,active_version,metadata_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)", [fresh.document.id, projectId, title, "draft", 0, "{}", fresh.document.createdAt, fresh.document.updatedAt]); return fresh; }
    const document = { ...docs[0], metadata: JSON.parse(String(docs[0].metadataJson ?? "{}")) } as unknown as ThesisDocument;
    const sections = await db.select<Record<string, unknown>[]>("SELECT id,document_id AS documentId,project_id AS projectId,parent_id AS parentId,sort_order AS sortOrder,heading_level AS headingLevel,title,content,content_format AS contentFormat,word_count AS wordCount,purpose,target_length AS targetLength,source_plan_json AS sourcePlanJson,created_at AS createdAt,updated_at AS updatedAt FROM thesis_sections WHERE document_id=? ORDER BY parent_id,sort_order", [document.id]);
    const revisions = await db.select<Record<string, unknown>[]>("SELECT id,document_id AS documentId,project_id AS projectId,version_number AS versionNumber,source,label,snapshot_json AS snapshotJson,content_hash AS contentHash,created_at AS createdAt FROM thesis_revisions WHERE document_id=? ORDER BY version_number DESC", [document.id]);
    const citations = await db.select<ThesisCitation[]>("SELECT id,project_id AS projectId,document_id AS documentId,section_id AS sectionId,literature_id AS literatureId,anchor,locator,prefix,suffix,render_text AS renderText,source_hash AS sourceHash,created_at AS createdAt,updated_at AS updatedAt FROM thesis_citations WHERE document_id=?", [document.id]);
    const links = await db.select<ThesisSourceLink[]>("SELECT id,project_id AS projectId,document_id AS documentId,section_id AS sectionId,source_type AS sourceType,source_id AS sourceId,locator,label,status,snapshot_text AS snapshotText,source_hash AS sourceHash,evidence_id AS evidenceId,artifact_id AS artifactId,run_id AS runId,created_at AS createdAt,updated_at AS updatedAt FROM thesis_source_links WHERE document_id=?", [document.id]);
    const proposals = await db.select<Record<string, unknown>[]>("SELECT id,project_id AS projectId,document_id AS documentId,section_id AS sectionId,operation,original_text AS originalText,proposed_text AS proposedText,used_source_ids_json AS usedSourceIdsJson,unsupported_json AS unsupportedJson,model,prompt_version AS promptVersion,context_ids_json AS contextIdsJson,output_hash AS outputHash,status,created_at AS createdAt,resolved_at AS resolvedAt FROM thesis_ai_proposals WHERE document_id=? ORDER BY created_at DESC", [document.id]);
    return { document, sections: sections.map((s) => ({ ...s, sourcePlan: JSON.parse(String(s.sourcePlanJson ?? "[]")) })) as unknown as ThesisSection[], revisions: revisions.map((r) => ({ ...r, snapshot: JSON.parse(String(r.snapshotJson)) })) as unknown as ThesisRevision[], citations, links, proposals: proposals.map((p) => ({ ...p, usedSourceIds: JSON.parse(String(p.usedSourceIdsJson ?? "[]")), unsupported: JSON.parse(String(p.unsupportedJson ?? "[]")), contextIds: JSON.parse(String(p.contextIdsJson ?? "[]")) })) as unknown as ThesisAiProposal[] };
  }
  private async persist(workspace: WritingWorkspace) { localStorage.setItem(storageKey(workspace.document.projectId), JSON.stringify(workspace)); }
  async saveSections(workspace: WritingWorkspace, sections: ThesisSection[], source: WritingSource = "student", label = "自动保存") {
    const timestamp = now(); const normalized = sections.map((s) => ({ ...s, wordCount: countWords(s.content), updatedAt: timestamp })); const contentHash = await hash(normalized); const revision: ThesisRevision = { id: id(), documentId: workspace.document.id, projectId: workspace.document.projectId, versionNumber: workspace.document.activeVersion + 1, source, label, snapshot: normalized, contentHash, createdAt: timestamp };
    const next = { ...workspace, document: { ...workspace.document, activeVersion: revision.versionNumber, status: "active" as const, updatedAt: timestamp }, sections: normalized, revisions: [revision, ...workspace.revisions] };
    if (!desktop()) { await this.persist(next); return next; }
    const db = await getDatabase(); await db.execute("BEGIN");
    try { for (const section of normalized) await db.execute("INSERT INTO thesis_sections (id,document_id,project_id,parent_id,sort_order,heading_level,title,content,content_format,word_count,purpose,target_length,source_plan_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET parent_id=excluded.parent_id,sort_order=excluded.sort_order,heading_level=excluded.heading_level,title=excluded.title,content=excluded.content,word_count=excluded.word_count,purpose=excluded.purpose,target_length=excluded.target_length,source_plan_json=excluded.source_plan_json,updated_at=excluded.updated_at", [section.id, section.documentId, section.projectId, section.parentId, section.sortOrder, section.headingLevel, section.title, section.content, section.contentFormat, section.wordCount, section.purpose, section.targetLength, JSON.stringify(section.sourcePlan), section.createdAt, timestamp]); await db.execute("INSERT INTO thesis_revisions (id,document_id,project_id,version_number,source,label,snapshot_json,content_hash,created_at) VALUES (?,?,?,?,?,?,?,?,?)", [revision.id, revision.documentId, revision.projectId, revision.versionNumber, revision.source, revision.label, JSON.stringify(revision.snapshot), revision.contentHash, revision.createdAt]); await db.execute("UPDATE thesis_documents SET status='active',active_version=?,updated_at=? WHERE id=? AND project_id=?", [revision.versionNumber, timestamp, workspace.document.id, workspace.document.projectId]); await db.execute("COMMIT"); return next; } catch (error) { await db.execute("ROLLBACK"); throw error; }
  }
  async saveCitation(workspace: WritingWorkspace, input: Omit<ThesisCitation, "id" | "createdAt" | "updatedAt" | "sourceHash"> & { sourceHash?: string }) { const timestamp = now(); const citation = { ...input, id: id(), sourceHash: input.sourceHash ?? await hash(input), createdAt: timestamp, updatedAt: timestamp }; const next = { ...workspace, citations: [...workspace.citations, citation] }; if (!desktop()) { await this.persist(next); return next; } const db = await getDatabase(); await db.execute("INSERT INTO thesis_citations (id,project_id,document_id,section_id,literature_id,anchor,locator,prefix,suffix,render_text,source_hash,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)", [citation.id,citation.projectId,citation.documentId,citation.sectionId,citation.literatureId,citation.anchor,citation.locator,citation.prefix,citation.suffix,citation.renderText,citation.sourceHash,citation.createdAt,citation.updatedAt]); return next; }
  async saveSourceLink(workspace: WritingWorkspace, input: Omit<ThesisSourceLink, "id" | "createdAt" | "updatedAt" | "sourceHash"> & { sourceHash?: string }) { const timestamp = now(); const link = { ...input, id: id(), sourceHash: input.sourceHash ?? await hash(input.snapshotText), createdAt: timestamp, updatedAt: timestamp }; const next = { ...workspace, links: [...workspace.links.filter((item) => !(item.sectionId === link.sectionId && item.sourceType === link.sourceType && item.sourceId === link.sourceId)), link] }; if (!desktop()) { await this.persist(next); return next; } const db = await getDatabase(); await db.execute("INSERT INTO thesis_source_links (id,project_id,document_id,section_id,source_type,source_id,locator,label,status,snapshot_text,source_hash,evidence_id,artifact_id,run_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(section_id,source_type,source_id) DO UPDATE SET locator=excluded.locator,label=excluded.label,status=excluded.status,snapshot_text=excluded.snapshot_text,source_hash=excluded.source_hash,evidence_id=excluded.evidence_id,artifact_id=excluded.artifact_id,run_id=excluded.run_id,updated_at=excluded.updated_at", [link.id,link.projectId,link.documentId,link.sectionId,link.sourceType,link.sourceId,link.locator,link.label,link.status,link.snapshotText,link.sourceHash,link.evidenceId ?? null,link.artifactId ?? null,link.runId ?? null,link.createdAt,link.updatedAt]); return next; }
  async saveProposal(workspace: WritingWorkspace, input: Omit<ThesisAiProposal, "id" | "createdAt" | "resolvedAt" | "outputHash">) { const proposal = { ...input, id: id(), outputHash: await hash(input.proposedText), createdAt: now(), resolvedAt: null }; const next = { ...workspace, proposals: [proposal, ...workspace.proposals] }; if (!desktop()) { await this.persist(next); return next; } const db = await getDatabase(); await db.execute("INSERT INTO thesis_ai_proposals (id,project_id,document_id,section_id,operation,original_text,proposed_text,used_source_ids_json,unsupported_json,model,prompt_version,context_ids_json,output_hash,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", [proposal.id,proposal.projectId,proposal.documentId,proposal.sectionId,proposal.operation,proposal.originalText,proposal.proposedText,JSON.stringify(proposal.usedSourceIds),JSON.stringify(proposal.unsupported),proposal.model,proposal.promptVersion,JSON.stringify(proposal.contextIds),proposal.outputHash,proposal.status,proposal.createdAt]); return next; }
  async resolveProposal(workspace: WritingWorkspace, proposalId: string, status: ThesisAiProposal["status"]) { const timestamp = now(); const next = { ...workspace, proposals: workspace.proposals.map((p) => p.id === proposalId ? { ...p, status, resolvedAt: timestamp } : p) }; if (!desktop()) { await this.persist(next); return next; } const db = await getDatabase(); await db.execute("UPDATE thesis_ai_proposals SET status=?,resolved_at=? WHERE id=? AND project_id=?", [status, timestamp, proposalId, workspace.document.projectId]); return next; }
  async recordExport(workspace: WritingWorkspace, outputPath: string, fileHash: string, warnings: string[] = [], manualCheck: string[] = []): Promise<ThesisExportManifest> { const manifest: ThesisExportManifest = { id: id(), projectId: workspace.document.projectId, documentId: workspace.document.id, revisionId: workspace.revisions[0]?.id ?? "", outputPath, outputFormat: "docx", fileHash, requirementsVersion: null, templateVersion: "phase8-minimal-docx-v1", warnings, manualCheck, createdAt: now() }; if (!desktop()) { const next = { ...workspace, document: { ...workspace.document, metadata: { ...workspace.document.metadata, lastExport: manifest } } }; await this.persist(next); return manifest; } const db = await getDatabase(); await db.execute("INSERT INTO thesis_export_manifests (id,project_id,document_id,revision_id,output_path,output_format,file_hash,requirements_version,template_version,warnings_json,manual_check_json,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)", [manifest.id,manifest.projectId,manifest.documentId,manifest.revisionId,manifest.outputPath,manifest.outputFormat,manifest.fileHash,manifest.requirementsVersion,manifest.templateVersion,JSON.stringify(manifest.warnings),JSON.stringify(manifest.manualCheck),manifest.createdAt]); return manifest; }
  async listExports(projectId: string): Promise<ThesisExportManifest[]> { if (!desktop()) { const raw = localStorage.getItem(storageKey(projectId)); const metadata = raw ? (JSON.parse(raw) as WritingWorkspace).document.metadata : {}; const lastExport = metadata.lastExport as ThesisExportManifest | undefined; return lastExport ? [lastExport] : []; } const db = await getDatabase(); const rows = await db.select<Record<string, unknown>[]>("SELECT id,project_id AS projectId,document_id AS documentId,revision_id AS revisionId,output_path AS outputPath,output_format AS outputFormat,file_hash AS fileHash,requirements_version AS requirementsVersion,template_version AS templateVersion,warnings_json AS warningsJson,manual_check_json AS manualCheckJson,created_at AS createdAt FROM thesis_export_manifests WHERE project_id=? ORDER BY created_at DESC", [projectId]); return rows.map((row) => ({ ...row, warnings: JSON.parse(String(row.warningsJson ?? "[]")), manualCheck: JSON.parse(String(row.manualCheckJson ?? "[]")) })) as unknown as ThesisExportManifest[]; }
}
export const writingService = new WritingService();
