import * as XLSX from "xlsx";
import type { DocumentBlock, DocumentParseInput, DocumentParseResult, DocumentParser } from "@/types/document";
const csvMime = new Set(["text/csv", "application/csv"]);
const clean = (value: unknown) => String(value ?? "").replace(/\u00a0/g, " ").trim();
const parseCsvRow = (line: string) => { const cells: string[] = []; let current = ""; let quoted = false; for (let i = 0; i < line.length; i += 1) { const char = line[i]; if (char === '"' && line[i + 1] === '"') { current += '"'; i += 1; } else if (char === '"') quoted = !quoted; else if (char === "," && !quoted) { cells.push(current); current = ""; } else current += char; } cells.push(current); return cells; };
const decodeCsv = (bytes: Uint8Array) => { for (const encoding of ["utf-8", "gb18030", "gbk"]) { try { return new TextDecoder(encoding, { fatal: true }).decode(bytes).replace(/^\uFEFF/, ""); } catch { /* try fallback */ } } return new TextDecoder().decode(bytes).replace(/^\uFEFF/, ""); };

export class XlsxParser implements DocumentParser {
  readonly id = "sheetjs-xlsx"; readonly version = "1.0.0";
  supports(input: Pick<DocumentParseInput, "mimeType">) { return input.mimeType === "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"; }
  async parse(input: DocumentParseInput): Promise<DocumentParseResult> {
    if (!input.bytes) return { status: "failed", warnings: [], error: { code: "io_error", message: "XLSX parser requires local bytes.", recoverable: true } };
    try { const workbook = XLSX.read(input.bytes, { type: "array", cellFormula: true, cellText: true }); const blocks: DocumentBlock[] = []; let order = 0;
      workbook.SheetNames.forEach((sheetName, sheetIndex) => { const sheet = workbook.Sheets[sheetName]; const range = sheet["!ref"] ?? "A1:A1"; const decoded = XLSX.utils.decode_range(range); blocks.push({ id: `${input.documentId}:sheet:${sheetIndex}`, type: "table", text: sheetName, order: order++, locator: { format: "xlsx", sheet: sheetName, cellRange: range }, metadata: { usedRange: range } }); for (let row = decoded.s.r; row <= decoded.e.r; row += 1) { const rowValues: string[] = []; const rowStart = XLSX.utils.encode_cell({ r: row, c: decoded.s.c }); const rowEnd = XLSX.utils.encode_cell({ r: row, c: decoded.e.c }); for (let col = decoded.s.c; col <= decoded.e.c; col += 1) { const address = XLSX.utils.encode_cell({ r: row, c: col }); const cell = sheet[address]; const value = clean(cell?.f ? `=${cell.f.replace(/^=/, "")}` : cell?.v); rowValues.push(value); blocks.push({ id: `${input.documentId}:cell:${address}`, type: "table_cell", text: value, order: order++, locator: { format: "xlsx", sheet: sheetName, cellRange: address }, metadata: { row: row + 1, column: col + 1, formula: cell?.f ?? null } }); } blocks.push({ id: `${input.documentId}:row:${sheetName}:${row + 1}`, type: "table_row", text: rowValues.join("\t"), order: order++, locator: { format: "xlsx", sheet: sheetName, cellRange: `${rowStart}:${rowEnd}` }, metadata: { row: row + 1 } }); } });
      return { status: "parsed", warnings: [], document: { documentId: input.documentId, projectFileId: input.projectFileId, title: input.title, mimeType: input.mimeType, language: null, pageCount: null, blocks, metadata: { sheetNames: workbook.SheetNames }, warnings: [] } };
    } catch (error) { return { status: "failed", warnings: [], error: { code: "invalid_document", message: error instanceof Error ? error.message : "Unable to parse XLSX.", recoverable: false } }; }
  }
}
export class CsvParser implements DocumentParser {
  readonly id = "csv-local"; readonly version = "1.0.0";
  supports(input: Pick<DocumentParseInput, "mimeType">) { return input.mimeType !== null && csvMime.has(input.mimeType); }
  async parse(input: DocumentParseInput): Promise<DocumentParseResult> { if (!input.bytes) return { status: "failed", warnings: [], error: { code: "io_error", message: "CSV parser requires local bytes.", recoverable: true } }; const rows = decodeCsv(input.bytes).split(/\r?\n/).filter((line) => line.length > 0).map(parseCsvRow); const blocks: DocumentBlock[] = []; let order = 0; rows.forEach((row, rowIndex) => { blocks.push({ id: `${input.documentId}:row:${rowIndex + 1}`, type: "table_row", text: row.join("\t"), order: order++, locator: { format: "txt_md", lineStart: rowIndex + 1, lineEnd: rowIndex + 1 }, metadata: { row: rowIndex + 1 } }); row.forEach((text, col) => blocks.push({ id: `${input.documentId}:cell:${rowIndex + 1}:${col + 1}`, type: "table_cell", text, order: order++, locator: { format: "txt_md", lineStart: rowIndex + 1, lineEnd: rowIndex + 1 }, metadata: { row: rowIndex + 1, column: col + 1 } })); }); return { status: "parsed", warnings: [], document: { documentId: input.documentId, projectFileId: input.projectFileId, title: input.title, mimeType: input.mimeType, language: null, pageCount: null, blocks, metadata: { headers: rows[0] ?? [], rowCount: rows.length }, warnings: [] } }; }
}
