import { useState } from "react";
import { AlertTriangle, CheckCircle2, FileText, Plus, Save, Send, Sparkles } from "lucide-react";
import { mockAdvisorComments, mockIssues, mockRules, stageGates, stageStates, type StageState } from "@/data/mock/workflow";
import { mockThesisProject } from "@/data/mock/thesis-project";
import "./foundation.css";

type Kind = "requirements" | "topic" | "task" | "translation" | "midterm" | "reviewer" | "files" | "calendar" | "settings";
const config: Record<Kind,{title:string; eyebrow:string; state:StageState; description:string}> = { requirements:{title:"论文要求",eyebrow:"准备阶段 / 学院规范",state:"active",description:"集中核对篇幅、文献、格式与提交要求。"}, topic:{title:"选题",eyebrow:"准备阶段 / 研究方向",state:"completed",description:"记录选题依据、研究边界与导师确认。"}, task:{title:"任务书",eyebrow:"准备阶段 / 培养任务",state:"completed",description:"任务目标、研究内容、时间节点与责任确认。"}, translation:{title:"外文翻译",eyebrow:"写作阶段 / 翻译材料",state:"overdue",description:"外文原文、翻译稿与术语核对工作区。"}, midterm:{title:"中期检查",eyebrow:"写作阶段 / 阶段检查",state:"completed",description:"检查研究进度、阶段成果和待改进问题。"}, reviewer:{title:"评阅教师评阅",eyebrow:"定稿阶段 / 预演记录",state:"pending",description:"模拟评阅记录，正式结论以学院通知为准。"}, files:{title:"文件中心",eyebrow:"完成阶段 / 文件管理",state:"active",description:"统一查看项目文件与版本来源。"}, calendar:{title:"节点日历",eyebrow:"项目管理 / 时间节点",state:"active",description:"展示论文流程的重要日期与提醒。"}, settings:{title:"设置",eyebrow:"工作台 / 偏好设置",state:"active",description:"本地界面与通知偏好 Mock 设置。"} };
function Badge({state}:{state:StageState}){const item=stageStates[state];return <span className={`foundation-badge ${item.tone}`}>{item.label}</span>}
export function FoundationPage({kind}:{kind:Kind}){const item=config[kind];const [notice,setNotice]=useState("");const gate=kind==="translation"?stageGates.implementation:undefined;const cards=kind==="requirements"?mockRules:kind==="files"?mockThesisProject.recentFiles.map(x=>({label:x.name,value:`${x.type} · ${x.updatedAt}`,state:"active" as StageState})):kind==="calendar"?mockThesisProject.milestones.map(x=>({label:x.title,value:`${x.date} · ${x.detail}`,state:x.status==="completed"?"completed":"pending" as StageState})):mockAdvisorComments.map(x=>({label:`${x.author} ${x.id}`,value:x.content,state:x.state}));return <section className="foundation-page"><header><div><p>{item.eyebrow}</p><h1>{item.title}</h1><span>{mockThesisProject.title}</span></div><div><Badge state={item.state}/><button onClick={()=>setNotice("已保存为本地 Mock 记录") }><Save size={14}/>保存</button><button className="primary" disabled={Boolean(gate)} onClick={()=>setNotice("操作已记录（Mock）")}><Send size={14}/>提交/确认</button></div></header>{gate&&<div className="foundation-gate"><AlertTriangle size={15}/><span>{gate.reason}，当前页面仅可查看与完善材料。</span></div>}<p className="foundation-description">{item.description}</p><div className="foundation-grid">{cards.map(card=><article key={card.label}><header><FileText size={16}/><b>{card.label}</b><Badge state={card.state}/></header><p>{card.value}</p><button onClick={()=>setNotice(`已打开“${card.label}”的编辑入口（Mock）`)}>查看/编辑 <Plus size={13}/></button></article>)}</div><section className="foundation-work"><header><div><h2>当前工作</h2><span>集中 Mock 数据联动</span></div><button onClick={()=>setNotice("已创建关联修改任务（Mock）")}><Sparkles size={14}/>创建修改任务</button></header>{mockIssues.map(issue=><p key={issue.id}><CheckCircle2 size={14}/><b>{issue.title}</b><span>{issue.source}</span><Badge state={issue.state}/></p>)}</section>{notice&&<div className="foundation-toast"><CheckCircle2 size={14}/>{notice}<button onClick={()=>setNotice("")}>×</button></div>}</section>}
