export type WritingSource = "student" | "ai" | "restore" | "import";
export type SourceType = "literature" | "note" | "card" | "requirement" | "evidence" | "artifact";
export interface ThesisDocument { id: string; projectId: string; title: string; status: "draft" | "active" | "archived"; activeVersion: number; metadata: Record<string, unknown>; createdAt: string; updatedAt: string; }
export interface ThesisSection { id: string; documentId: string; projectId: string; parentId: string | null; sortOrder: number; headingLevel: number; title: string; content: string; contentFormat: "html" | "plain_text"; wordCount: number; purpose: string; targetLength: number | null; sourcePlan: string[]; createdAt: string; updatedAt: string; }
export interface ThesisRevision { id: string; documentId: string; projectId: string; versionNumber: number; source: WritingSource; label: string; snapshot: ThesisSection[]; contentHash: string; createdAt: string; }
export interface ThesisCitation { id: string; projectId: string; documentId: string; sectionId: string; literatureId: string; anchor: string; locator: string | null; prefix: string; suffix: string; renderText: string; sourceHash: string; createdAt: string; updatedAt: string; }
export interface ThesisSourceLink { id: string; projectId: string; documentId: string; sectionId: string; sourceType: SourceType; sourceId: string; locator: string | null; label: string; status: "linked" | "stale" | "broken"; snapshotText: string; sourceHash: string; evidenceId?: string | null; artifactId?: string | null; runId?: string | null; createdAt: string; updatedAt: string; }
export interface ThesisAiProposal { id: string; projectId: string; documentId: string; sectionId: string; operation: string; originalText: string; proposedText: string; usedSourceIds: string[]; unsupported: string[]; model: string; promptVersion: string; contextIds: string[]; outputHash: string; status: "pending" | "accepted" | "rejected" | "undone"; createdAt: string; resolvedAt: string | null; }
export interface ThesisExportManifest { id: string; projectId: string; documentId: string; revisionId: string; outputPath: string; outputFormat: "docx" | "pdf"; fileHash: string; requirementsVersion: string | null; templateVersion: string | null; warnings: string[]; manualCheck: string[]; createdAt: string; }
export interface CitationAudit { citationCount: number; distinctLiteratureCount: number; orphanCount: number; duplicateAnchorCount: number; staleCount: number; }
export interface WritingWorkspace { document: ThesisDocument; sections: ThesisSection[]; revisions: ThesisRevision[]; citations: ThesisCitation[]; links: ThesisSourceLink[]; proposals: ThesisAiProposal[]; }
