import type { AIError, AIProvider, AIRequest, AIResponse, AIStreamEvent, AIUsage, AIRun, AIRunStatus, ResolvedProviderConfig } from "@/ai/domain";
import { structuredOutputs } from "@/ai/structuredOutputRegistry";

export interface AITaskInput { projectId: string; providerKey: string; modelId: string; request: AIRequest; secretRef: string; connectionTimeoutMs?: number; totalTimeoutMs?: number; maxRetries?: number; }
export interface AIRunOutput { id: string; aiRunId: string; outputType: string; textContent: string | null; structuredJson: unknown | null; schemaKey: string | null; schemaVersion: string | null; validationStatus: "valid" | "invalid" | "not_applicable"; createdAt: string; }
export interface AIRunRepository { create(run: AIRun): Promise<void>; update(id: string, changes: Partial<AIRun>): Promise<void>; get(id: string): Promise<AIRun | null>; listProject(projectId: string): Promise<AIRun[]>; persistOutput(output: AIRunOutput): Promise<void>; getOutput?(runId: string): Promise<AIRunOutput | null>; appendStream?(runId: string, text: string): Promise<void>; }
export interface SecretResolver { resolve(secretRef: string): Promise<ResolvedProviderConfig>; }
export interface ProviderLookup { get(key: string): AIProvider; }
export type TaskEvent = { runId: string; projectId: string; event: AIStreamEvent };
const now = () => new Date().toISOString(); const id = () => crypto.randomUUID();

export class AITaskEngine {
  private readonly active = new Map<string, { projectId: string; controller: AbortController }>();
  private readonly projectCounts = new Map<string, number>(); private running = 0;
  constructor(private readonly providers: ProviderLookup, private readonly secrets: SecretResolver, private readonly runs: AIRunRepository, private readonly limits = { global: 3, perProject: 1, streamFlushMs: 200, defaultTimeoutMs: 60_000 }) {}
  async runAITask(task: AITaskInput): Promise<AIRun> { return this.execute(task); }
  async *streamAITask(task: AITaskInput): AsyncIterable<TaskEvent> { const emitted: TaskEvent[] = []; const run = await this.execute(task, (event) => emitted.push(event)); for (const event of emitted) yield event; yield { runId: run.id, projectId: run.projectId!, event: { type: "completed", response: { text: "" } } }; }
  async cancelAIRun(runId: string): Promise<void> { const active = this.active.get(runId); if (active) active.controller.abort(); const run = await this.runs.get(runId); if (run && (run.status === "queued" || run.status === "running" || run.status === "streaming")) await this.runs.update(runId, { status: "cancelled", cancelledAt: now(), completedAt: now() }); }
  async retryAIRun(runId: string): Promise<AIRun> { const run = await this.getAIRun(runId); if (!run) throw new Error("AI run not found"); if (!(["failed", "timed_out", "cancelled"] as AIRunStatus[]).includes(run.status)) throw new Error("Only completed failure states can retry"); throw new Error("Retry requires the original task payload; the engine intentionally does not persist prompts."); }
  getAIRun(runId: string) { return this.runs.get(runId); } getAIRunOutput(runId: string) { return this.runs.getOutput?.(runId) ?? Promise.resolve(null); } listProjectAIRuns(projectId: string) { return this.runs.listProject(projectId); }
  private async execute(task: AITaskInput, emit?: (event: TaskEvent) => void): Promise<AIRun> {
    const provider = this.providers.get(task.providerKey); const capabilities = provider.getCapabilities(task.modelId); if (!task.request.task.requiredCapabilities.every((capability) => capabilities.has(capability))) throw new Error("Selected model lacks a required task capability");
    const run: AIRun = { id: id(), projectId: task.projectId, taskKey: task.request.task.key, providerKey: task.providerKey, modelId: task.modelId, promptTemplateKey: task.request.prompt.key, promptTemplateVersion: task.request.prompt.version, contextManifest: task.request.context.manifest, status: "queued", startedAt: now(), completedAt: null, cancelledAt: null, error: null, requestId: task.request.requestId, providerRequestId: null, usage: null };
    await this.runs.create(run); await this.acquire(run); const controller = new AbortController(); this.active.set(run.id, { projectId: task.projectId, controller }); let timer: ReturnType<typeof setTimeout> | undefined; let timedOut = false;
    try { await this.runs.update(run.id, { status: "running" }); timer = setTimeout(() => { timedOut = true; controller.abort(); }, task.totalTimeoutMs ?? this.limits.defaultTimeoutMs); const config = await this.secrets.resolve(task.secretRef); let response: AIResponse | undefined; let text = ""; let usage: AIUsage | undefined; let lastFlush = 0;
      if (provider.getCapabilities(task.modelId).has("streaming")) { await this.runs.update(run.id, { status: "streaming" }); for await (const event of provider.stream(task.request, config, controller.signal)) { if (!this.isCurrent(run)) break; if (event.type === "text_delta") { text += event.text; emit?.({ runId: run.id, projectId: task.projectId, event }); if (this.runs.appendStream && Date.now() - lastFlush >= this.limits.streamFlushMs) { await this.runs.appendStream(run.id, text); lastFlush = Date.now(); } } else if (event.type === "usage") usage = event.usage; else if (event.type === "completed") response = { ...event.response, text: event.response.text || text, usage: event.response.usage ?? usage }; else if (event.type === "cancelled") controller.abort(); else if (event.type === "error") throw event.error; }
      } else response = await this.withRetry(provider, task, config, controller.signal);
      if (controller.signal.aborted) throw new DOMException("Aborted", "AbortError"); response ??= { text, usage }; if (!this.isCurrent(run)) return (await this.runs.get(run.id))!;
      let validationStatus: AIRunOutput["validationStatus"] = "not_applicable"; let validationError: AIError | null = null;
      if (task.request.structuredOutput) { const schema = structuredOutputs.get(task.request.structuredOutput.key, task.request.structuredOutput.version); const result = schema.validate(response.structured, task.request.context.items.filter((item) => item.type === "source").map((item) => item.id)); validationStatus = result.valid ? "valid" : "invalid"; if (!result.valid) validationError = { code: "schema_invalid", messageSafe: "Model returned invalid structured output.", retryable: false }; }
      const output: AIRunOutput = { id: id(), aiRunId: run.id, outputType: response.structured ? "structured" : "text", textContent: response.text || null, structuredJson: response.structured ?? null, schemaKey: task.request.structuredOutput?.key ?? null, schemaVersion: task.request.structuredOutput?.version ?? null, validationStatus, createdAt: now() }; await this.runs.persistOutput(output); await this.runs.update(run.id, validationError ? { status: "failed", completedAt: now(), error: validationError, usage: response.usage ?? usage ?? null } : { status: "succeeded", completedAt: now(), usage: response.usage ?? usage ?? null, providerRequestId: response.providerRequestId ?? null }); return (await this.runs.get(run.id))!;
    } catch (cause) { const error = timedOut ? { code: "timeout", messageSafe: "Provider request timed out.", retryable: true } : provider.normalizeError(cause); const status: AIRunStatus = timedOut || error.code === "timeout" ? "timed_out" : error.code === "cancelled" || controller.signal.aborted ? "cancelled" : "failed"; if (this.isCurrent(run) || timedOut) await this.runs.update(run.id, { status, completedAt: now(), cancelledAt: status === "cancelled" ? now() : null, error }); return (await this.runs.get(run.id))!;
    } finally { if (timer) clearTimeout(timer); this.active.delete(run.id); this.release(run); }
  }
  private async withRetry(provider: AIProvider, task: AITaskInput, config: ResolvedProviderConfig, signal: AbortSignal): Promise<AIResponse> { const attempts = task.maxRetries ?? 2; for (let n = 0;; n++) { try { return await provider.generate(task.request, config, signal); } catch (cause) { const error = provider.normalizeError(cause); if (n >= attempts || !error.retryable || signal.aborted) throw cause; await new Promise<void>((resolve, reject) => { const timeout = setTimeout(resolve, Math.min(1000, 100 * 2 ** n) + Math.floor(Math.random() * 30)); signal.addEventListener("abort", () => { clearTimeout(timeout); reject(new DOMException("Aborted", "AbortError")); }, { once: true }); }); } } }
  private isCurrent(run: AIRun) { const active = this.active.get(run.id); return !!active && active.projectId === run.projectId && !active.controller.signal.aborted; }
  private async acquire(run: AIRun) { if (this.running >= this.limits.global || (this.projectCounts.get(run.projectId!) ?? 0) >= this.limits.perProject) throw new Error("AI task queue is full"); this.running++; this.projectCounts.set(run.projectId!, (this.projectCounts.get(run.projectId!) ?? 0) + 1); }
  private release(run: AIRun) { this.running--; this.projectCounts.set(run.projectId!, Math.max(0, (this.projectCounts.get(run.projectId!) ?? 1) - 1)); }
}
