import { getDatabase } from "@/lib/database";
import type { ProjectFile } from "@/types/domain";
export class FileRepository {
  async listByProject(projectId:string):Promise<ProjectFile[]>{const db=await getDatabase();return db.select<ProjectFile[]>("SELECT id,project_id AS projectId,workflow_stage_id AS workflowStageId,original_name AS originalName,stored_name AS storedName,relative_path AS relativePath,mime_type AS mimeType,extension,size_bytes AS sizeBytes,checksum,file_category AS fileCategory,version_label AS versionLabel,source,created_at AS createdAt,updated_at AS updatedAt FROM project_files WHERE project_id = ? ORDER BY updated_at DESC",[projectId]);}
  async findById(id:string):Promise<ProjectFile|null>{const db=await getDatabase();const rows=await db.select<ProjectFile[]>("SELECT id,project_id AS projectId,workflow_stage_id AS workflowStageId,original_name AS originalName,stored_name AS storedName,relative_path AS relativePath,mime_type AS mimeType,extension,size_bytes AS sizeBytes,checksum,file_category AS fileCategory,version_label AS versionLabel,source,created_at AS createdAt,updated_at AS updatedAt FROM project_files WHERE id = ?",[id]);return rows[0]??null;}
  async create(file:ProjectFile):Promise<ProjectFile>{const db=await getDatabase();await db.execute("INSERT INTO project_files (id,project_id,workflow_stage_id,original_name,stored_name,relative_path,mime_type,extension,size_bytes,checksum,file_category,version_label,source,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[file.id,file.projectId,file.workflowStageId,file.originalName,file.storedName,file.relativePath,file.mimeType,file.extension,file.sizeBytes,file.checksum,file.fileCategory,file.versionLabel,file.source,file.createdAt,file.updatedAt]);return file;}
  async update(id:string,changes:Partial<Omit<ProjectFile,"id"|"projectId"|"createdAt">>):Promise<ProjectFile|null>{const map:Record<string,string>={workflowStageId:"workflow_stage_id",originalName:"original_name",storedName:"stored_name",relativePath:"relative_path",mimeType:"mime_type",extension:"extension",sizeBytes:"size_bytes",checksum:"checksum",fileCategory:"file_category",versionLabel:"version_label",source:"source",updatedAt:"updated_at"};const entries=Object.entries(changes).filter(([,v])=>v!==undefined);if(!entries.length)return this.findById(id);const db=await getDatabase();await db.execute(`UPDATE project_files SET ${entries.map(([k])=>`${map[k]} = ?`).join(", ")} WHERE id = ?`,[...entries.map(([,v])=>v),id]);return this.findById(id);}
  async delete(id:string):Promise<void>{const db=await getDatabase();await db.execute("DELETE FROM project_files WHERE id = ?",[id]);}
}
