import { getDatabase } from "@/lib/database";
export type WorkspaceRow = { id:string; title:string; year:number|null; venue:string|null; literatureType:string; status:string; verificationStatus:string; updatedAt:string; authors:string; doi:string|null; tags:string; hasFulltext:boolean; primaryFileId:string|null; cardStatus:string|null; };
const authorSql = `COALESCE((SELECT group_concat(author_name, '; ') FROM (SELECT trim(COALESCE(a.family_name,a.literal_name)||CASE WHEN a.given_name<>'' THEN ', '||a.given_name ELSE '' END) AS author_name FROM literature_item_authors ia JOIN literature_authors a ON a.id=ia.author_id WHERE ia.literature_id=l.id ORDER BY ia.author_order)), '') AS authors`;
const doiSql = `(SELECT normalized_value FROM literature_identifiers i WHERE i.literature_id=l.id AND i.scheme='doi' ORDER BY i.verified DESC LIMIT 1) AS doi`;
const tagSql = `COALESCE((SELECT group_concat(t.name, ', ') FROM literature_item_tags it JOIN literature_tags t ON t.id=it.tag_id WHERE it.literature_id=l.id), '') AS tags`;
const fulltextSql = `EXISTS(SELECT 1 FROM literature_files f WHERE f.literature_id=l.id AND f.relation_type='fulltext') AS hasFulltext`;
const primaryFileSql = `(SELECT project_file_id FROM literature_files f WHERE f.literature_id=l.id AND f.relation_type='fulltext' ORDER BY f.is_primary DESC, f.created_at ASC LIMIT 1) AS primaryFileId`;
const cardSql = `(SELECT status FROM literature_cards c WHERE c.literature_id=l.id ORDER BY c.updated_at DESC LIMIT 1) AS cardStatus`;
const base = `SELECT l.id,l.title,l.year,l.venue,l.literature_type AS literatureType,l.status,l.verification_status AS verificationStatus,l.updated_at AS updatedAt,${authorSql},${doiSql},${tagSql},${fulltextSql},${primaryFileSql},${cardSql} FROM literature_items l`;
export class LiteratureWorkspaceRepository{
 async list(projectId:string,view="all"):Promise<WorkspaceRow[]>{const where=["l.project_id=?"];if(view==="inbox")where.push("l.status='inbox'");if(view==="unread")where.push("l.status='unread'");if(view==="reading")where.push("l.status='reading'");if(view==="read")where.push("l.status='read'");if(view==="conflict")where.push("l.verification_status='conflict'");if(view==="unverified")where.push("l.verification_status='unverified'");if(view==="has_fulltext")where.push("EXISTS(SELECT 1 FROM literature_files f WHERE f.literature_id=l.id AND f.relation_type='fulltext')");if(view==="no_fulltext")where.push("NOT EXISTS(SELECT 1 FROM literature_files f WHERE f.literature_id=l.id AND f.relation_type='fulltext')");if(view==="card_review")where.push("EXISTS(SELECT 1 FROM literature_cards c WHERE c.literature_id=l.id AND c.status='draft')");const db=await getDatabase();return db.select<WorkspaceRow[]>(`${base} WHERE ${where.join(" AND ")} ORDER BY l.updated_at DESC`,[projectId]);}
 async batchStatus(projectId:string,ids:string[],status:string){if(!ids.length)return;const db=await getDatabase();await db.execute(`UPDATE literature_items SET status=?,updated_at=? WHERE project_id=? AND id IN (${ids.map(()=>'?').join(',')})`,[status,new Date().toISOString(),projectId,...ids]);}
 async archive(projectId:string,ids:string[]){return this.batchStatus(projectId,ids,"archived");}
 async smartCounts(projectId:string){const rows=await this.list(projectId);return {all:rows.length,inbox:rows.filter(x=>x.status==="inbox").length,unread:rows.filter(x=>x.status==="unread").length,reading:rows.filter(x=>x.status==="reading").length,read:rows.filter(x=>x.status==="read").length,hasFulltext:rows.filter(x=>x.hasFulltext).length,conflict:rows.filter(x=>x.verificationStatus==="conflict").length,unverified:rows.filter(x=>x.verificationStatus==="unverified").length,cardReview:rows.filter(x=>x.cardStatus==="draft").length};}
}
