import { getDatabase } from "@/lib/database";
import type { FieldProvenance, Identifier, LiteratureChunk, LiteratureItem, MetadataCandidate } from "@/types/literature";

const itemSelect = "SELECT id,project_id AS projectId,title,subtitle,abstract,year,publication_date AS publicationDate,venue,volume,issue,pages,publisher,language,literature_type AS literatureType,status,verification_status AS verificationStatus,preferred_citation_key AS preferredCitationKey,created_at AS createdAt,updated_at AS updatedAt FROM literature_items";
export class LiteratureRepository {
  async create(item: LiteratureItem): Promise<void> { const db = await getDatabase(); await db.execute("INSERT INTO literature_items (id,project_id,title,subtitle,abstract,year,publication_date,venue,volume,issue,pages,publisher,language,literature_type,status,verification_status,preferred_citation_key,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", [item.id,item.projectId,item.title,item.subtitle,item.abstract,item.year,item.publicationDate,item.venue,item.volume,item.issue,item.pages,item.publisher,item.language,item.literatureType,item.status,item.verificationStatus,item.preferredCitationKey,item.createdAt,item.updatedAt]); }
  async find(projectId: string, id: string): Promise<LiteratureItem | null> { const db = await getDatabase(); return (await db.select<LiteratureItem[]>(`${itemSelect} WHERE project_id=? AND id=?`, [projectId,id]))[0] ?? null; }
  async list(projectId: string): Promise<LiteratureItem[]> { const db = await getDatabase(); return db.select<LiteratureItem[]>(`${itemSelect} WHERE project_id=? ORDER BY updated_at DESC`, [projectId]); }
  async addIdentifier(identifier: Identifier): Promise<void> { const db = await getDatabase(); await db.execute("INSERT INTO literature_identifiers (id,literature_id,scheme,value,normalized_value,source,verified) SELECT ?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM literature_items WHERE id=?)", [identifier.id,identifier.literatureId,identifier.scheme,identifier.value,identifier.normalizedValue,identifier.source,identifier.verified ? 1 : 0,identifier.literatureId]); }
  async saveMetadataCandidate(projectId: string, candidate: MetadataCandidate): Promise<void> { const db = await getDatabase(); await db.execute("INSERT INTO literature_metadata_sources (id,literature_id,source_type,source_name,external_id,fetched_at,raw_metadata_path,raw_metadata_json,confidence,created_at) SELECT ?,?,?,?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM literature_items WHERE id=? AND project_id=?) AND NOT EXISTS (SELECT 1 FROM literature_metadata_sources WHERE literature_id=? AND source_type=? AND source_name=? AND COALESCE(external_id,'')=COALESCE(?,'') AND COALESCE(raw_metadata_json,'')=COALESCE(?,''))", [candidate.id,candidate.literatureId,candidate.sourceType,candidate.sourceName,candidate.externalId,candidate.fetchedAt,candidate.rawMetadataPath,candidate.rawMetadataJson,candidate.confidence,candidate.createdAt,candidate.literatureId,projectId,candidate.literatureId,candidate.sourceType,candidate.sourceName,candidate.externalId,candidate.rawMetadataJson]); }
  async listIdentifiers(projectId: string, literatureId: string): Promise<Identifier[]> { const db = await getDatabase(); return db.select<Identifier[]>("SELECT i.id,i.literature_id AS literatureId,i.scheme,i.value,i.normalized_value AS normalizedValue,i.source,i.verified FROM literature_identifiers i JOIN literature_items l ON l.id=i.literature_id WHERE l.project_id=? AND l.id=?", [projectId,literatureId]); }
  async activeProvenance(projectId: string, literatureId: string): Promise<FieldProvenance[]> { const db = await getDatabase(); return db.select<FieldProvenance[]>("SELECT p.id,p.literature_id AS literatureId,p.field_name AS fieldName,p.value_json AS valueJson,p.source_type AS sourceType,p.source_ref AS sourceRef,p.trust_level AS trustLevel,p.is_active AS isActive,p.created_at AS createdAt FROM literature_field_provenance p JOIN literature_items l ON l.id=p.literature_id WHERE l.project_id=? AND l.id=? AND p.is_active=1", [projectId,literatureId]); }
  async lexicalSearch(projectId: string, query: string, limit = 100): Promise<Array<{ chunkId: string; literatureId: string; text: string }>> { const db = await getDatabase(); return db.select("SELECT c.id AS chunkId,c.literature_id AS literatureId,c.text FROM literature_chunks_fts f JOIN literature_chunks c ON c.rowid=f.rowid JOIN literature_items l ON l.id=c.literature_id WHERE l.project_id=? AND literature_chunks_fts MATCH ? ORDER BY bm25(literature_chunks_fts) LIMIT ?", [projectId,query,Math.max(1,Math.min(limit,500))]); }
  async search(projectId: string, query: string, filters: { title?: string; author?: string; venue?: string; yearFrom?: number; yearTo?: number; tagId?: string; collectionId?: string; status?: string } = {}, limit = 100): Promise<Array<{ chunkId: string; literatureId: string; text: string; rank: number; locatorJson: string }>> { const where = ["l.project_id=?", "literature_chunks_fts MATCH ?"]; const params: unknown[] = [projectId, query]; if (filters.title) { where.push("l.title LIKE ?"); params.push(`%${filters.title}%`); } if (filters.venue) { where.push("l.venue LIKE ?"); params.push(`%${filters.venue}%`); } if (filters.status) { where.push("l.status=?"); params.push(filters.status); } if (filters.yearFrom) { where.push("l.year>=?"); params.push(filters.yearFrom); } if (filters.yearTo) { where.push("l.year<=?"); params.push(filters.yearTo); } if (filters.author) { where.push("EXISTS (SELECT 1 FROM literature_item_authors ia JOIN literature_authors a ON a.id=ia.author_id WHERE ia.literature_id=l.id AND (a.family_name LIKE ? OR a.literal_name LIKE ?))"); params.push(`%${filters.author}%`,`%${filters.author}%`); } if (filters.tagId) { where.push("EXISTS (SELECT 1 FROM literature_item_tags it WHERE it.literature_id=l.id AND it.tag_id=?)"); params.push(filters.tagId); } if (filters.collectionId) { where.push("EXISTS (SELECT 1 FROM literature_collection_items ci WHERE ci.literature_id=l.id AND ci.collection_id=?)"); params.push(filters.collectionId); } const db=await getDatabase(); params.push(Math.max(1,Math.min(limit,500))); return db.select(`SELECT c.id AS chunkId,c.literature_id AS literatureId,c.text,c.locator_json AS locatorJson,bm25(literature_chunks_fts) AS rank FROM literature_chunks_fts JOIN literature_chunks c ON c.rowid=literature_chunks_fts.rowid JOIN literature_items l ON l.id=c.literature_id WHERE ${where.join(" AND ")} ORDER BY rank LIMIT ?`,params); }
  async replaceChunks(projectId: string, literatureId: string, parseId: string, chunks: LiteratureChunk[]): Promise<void> { const db=await getDatabase(); await db.execute("DELETE FROM literature_chunks WHERE literature_id=? AND document_parse_id=? AND EXISTS (SELECT 1 FROM literature_items WHERE id=? AND project_id=?)",[literatureId,parseId,literatureId,projectId]); for (const chunk of chunks) await db.execute("INSERT INTO literature_chunks (id,literature_id,project_file_id,document_parse_id,chunk_order,text,text_hash,token_estimate,heading_path,locator_json,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)",[chunk.id,chunk.literatureId,chunk.projectFileId,chunk.documentParseId,chunk.chunkOrder,chunk.text,chunk.textHash,chunk.tokenEstimate,chunk.headingPath,chunk.locatorJson,chunk.createdAt]); }
}
