import { getDatabase } from "@/lib/database";
import type { ThesisRequirement } from "@/types/domain";
export class RequirementRepository {
  async listByProject(projectId:string):Promise<ThesisRequirement[]>{const db=await getDatabase();return db.select<ThesisRequirement[]>("SELECT id,project_id AS projectId,requirement_key AS requirementKey,label,target_value AS targetValue,current_value AS currentValue,unit,status,description,created_at AS createdAt,updated_at AS updatedAt FROM thesis_requirements WHERE project_id=? ORDER BY requirement_key",[projectId]);}
  async findById(id:string):Promise<ThesisRequirement|null>{const db=await getDatabase();const rows=await db.select<ThesisRequirement[]>("SELECT id,project_id AS projectId,requirement_key AS requirementKey,label,target_value AS targetValue,current_value AS currentValue,unit,status,description,created_at AS createdAt,updated_at AS updatedAt FROM thesis_requirements WHERE id=?",[id]);return rows[0]??null;}
  async create(requirement:ThesisRequirement):Promise<ThesisRequirement>{const db=await getDatabase();await db.execute("INSERT INTO thesis_requirements (id,project_id,requirement_key,label,target_value,current_value,unit,status,description,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)",[requirement.id,requirement.projectId,requirement.requirementKey,requirement.label,requirement.targetValue,requirement.currentValue,requirement.unit,requirement.status,requirement.description,requirement.createdAt,requirement.updatedAt]);return requirement;}
  async update(id:string,changes:Partial<Omit<ThesisRequirement,"id"|"projectId"|"createdAt">>):Promise<ThesisRequirement|null>{const map:Record<string,string>={requirementKey:"requirement_key",label:"label",targetValue:"target_value",currentValue:"current_value",unit:"unit",status:"status",description:"description",updatedAt:"updated_at"};const entries=Object.entries(changes).filter(([,v])=>v!==undefined);if(!entries.length)return this.findById(id);const db=await getDatabase();await db.execute(`UPDATE thesis_requirements SET ${entries.map(([k])=>`${map[k]} = ?`).join(", ")} WHERE id = ?`,[...entries.map(([,v])=>v),id]);return this.findById(id);}
  async delete(id:string):Promise<void>{const db=await getDatabase();await db.execute("DELETE FROM thesis_requirements WHERE id=?",[id]);}
}
