import { getDatabase } from "@/lib/database";
import type { RuleCandidate } from "@/types/document";

export class RuleCandidateRepository {
  async listByProject(projectId: string): Promise<RuleCandidate[]> { const db = await getDatabase(); const rows = await db.select<Array<Record<string, unknown>>>("SELECT * FROM rule_candidates WHERE project_id = ? ORDER BY created_at DESC", [projectId]); return rows.map((row) => this.map(row)); }
  private map(row: Record<string, unknown>): RuleCandidate { return { id: String(row.id), projectId: String(row.project_id), projectFileId: String(row.project_file_id), documentParseId: String(row.document_parse_id), ruleKey: String(row.rule_key), category: String(row.category), value: JSON.parse(String(row.value_json)), unit: row.unit as string | null, rawText: String(row.raw_text), locator: JSON.parse(String(row.locator_json)), confidence: Number(row.confidence), extractor: String(row.extractor), condition: row.condition_json ? JSON.parse(String(row.condition_json)) : null, exception: row.exception_json ? JSON.parse(String(row.exception_json)) : null, status: row.status as RuleCandidate["status"], createdAt: String(row.created_at), updatedAt: String(row.updated_at) }; }
  async findById(id: string): Promise<RuleCandidate | null> { const db = await getDatabase(); const rows = await db.select<Array<Record<string, unknown>>>("SELECT * FROM rule_candidates WHERE id = ?", [id]); return rows[0] ? this.map(rows[0]) : null; }
  async createMany(candidates: RuleCandidate[]): Promise<void> { if (!candidates.length) return; const db = await getDatabase(); for (const item of candidates) await db.execute("INSERT INTO rule_candidates (id,project_id,project_file_id,document_parse_id,rule_key,category,value_json,unit,raw_text,locator_json,confidence,extractor,condition_json,exception_json,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", [item.id,item.projectId,item.projectFileId,item.documentParseId,item.ruleKey,item.category,JSON.stringify(item.value),item.unit,item.rawText,JSON.stringify(item.locator),item.confidence,item.extractor,item.condition ? JSON.stringify(item.condition) : null,item.exception ? JSON.stringify(item.exception) : null,item.status,item.createdAt,item.updatedAt]); }
  async setStatus(id: string, status: RuleCandidate["status"], updatedAt: string): Promise<void> { const db = await getDatabase(); await db.execute("UPDATE rule_candidates SET status = ?, updated_at = ? WHERE id = ?", [status, updatedAt, id]); }
}
