import { getDatabase } from "@/lib/database";
import type { WorkflowStage } from "@/types/domain";

export class WorkflowRepository {
  async listByProject(projectId: string): Promise<WorkflowStage[]> { const db = await getDatabase(); return db.select<WorkflowStage[]>("SELECT id, project_id AS projectId, stage_key AS stageKey, stage_number AS stageNumber, title, status, started_at AS startedAt, completed_at AS completedAt, deadline, progress, sort_order AS sortOrder, created_at AS createdAt, updated_at AS updatedAt FROM workflow_stages WHERE project_id = ? ORDER BY sort_order", [projectId]); }
  async findById(id: string): Promise<WorkflowStage | null> { const db = await getDatabase(); const rows = await db.select<WorkflowStage[]>("SELECT id, project_id AS projectId, stage_key AS stageKey, stage_number AS stageNumber, title, status, started_at AS startedAt, completed_at AS completedAt, deadline, progress, sort_order AS sortOrder, created_at AS createdAt, updated_at AS updatedAt FROM workflow_stages WHERE id = ?", [id]); return rows[0] ?? null; }
  async create(stage: WorkflowStage): Promise<WorkflowStage> { const db = await getDatabase(); await db.execute("INSERT INTO workflow_stages (id,project_id,stage_key,stage_number,title,status,started_at,completed_at,deadline,progress,sort_order,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)", [stage.id,stage.projectId,stage.stageKey,stage.stageNumber,stage.title,stage.status,stage.startedAt,stage.completedAt,stage.deadline,stage.progress,stage.sortOrder,stage.createdAt,stage.updatedAt]); return stage; }
  async update(id: string, changes: Partial<Omit<WorkflowStage, "id" | "projectId" | "createdAt">>): Promise<WorkflowStage | null> { const map: Record<string,string> = { stageKey:"stage_key",stageNumber:"stage_number",title:"title",status:"status",startedAt:"started_at",completedAt:"completed_at",deadline:"deadline",progress:"progress",sortOrder:"sort_order",updatedAt:"updated_at" }; const entries=Object.entries(changes).filter(([,v])=>v!==undefined); if(!entries.length)return this.findById(id); const db=await getDatabase(); await db.execute(`UPDATE workflow_stages SET ${entries.map(([key])=>`${map[key]} = ?`).join(", ")} WHERE id = ?`,[...entries.map(([,v])=>v),id]); return this.findById(id); }
  async delete(id: string): Promise<void> { const db = await getDatabase(); await db.execute("DELETE FROM workflow_stages WHERE id = ?", [id]); }
}
