import { useEffect, useState } from "react";
import { BookOpen, CheckCircle2, Plus, ShieldCheck, Sparkles } from "lucide-react";
import { PageHeader, SectionCard, ViewShell } from "@/components/common/ViewShell";
import { ProjectRequiredState } from "@/components/common/ProjectRequiredState";
import { useProjectStore } from "@/stores/project-store";
import { useRequirementStore } from "@/stores/requirement-store";
import { writingService } from "@/services/writingService";
import { askConfiguredProvider, getActiveBrowserProvider } from "@/ai/providerClient";
import type { ThesisSection, WritingWorkspace } from "@/types/writing";

const templates = [["引言", "说明研究问题、背景与意义"], ["文献综述", "整理真实文献与研究缺口"], ["研究设计", "描述方法、变量与数据来源"], ["实证结果", "呈现 Phase 7 可核验结果"], ["结论与讨论", "回答问题并说明局限"]] as const;
const makeSection = (workspace: WritingWorkspace, title: string, order: number): ThesisSection => ({ id: crypto.randomUUID(), documentId: workspace.document.id, projectId: workspace.document.projectId, parentId: null, sortOrder: order, headingLevel: 1, title, content: "", contentFormat: "html", wordCount: 0, purpose: "", targetLength: null, sourcePlan: [], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() });

export function OutlinePlannerPage() {
  const { projects, activeProjectId, loadProjects } = useProjectStore(); const requirements = useRequirementStore(); const project = projects.find((item) => item.id === activeProjectId) ?? projects[0];
  const [workspace, setWorkspace] = useState<WritingWorkspace | null>(null); const [customTitle, setCustomTitle] = useState(""); const [notice, setNotice] = useState("正在加载项目结构…"); const [aiProposal, setAiProposal] = useState<string[] | null>(null); const [aiBusy, setAiBusy] = useState(false);
  useEffect(() => { void loadProjects(); }, [loadProjects]);
  useEffect(() => { if (!project) return; void Promise.all([writingService.load(project.id, project.title), requirements.load(project.id)]).then(([loaded]) => { setWorkspace(loaded); setNotice(loaded.sections.length ? "已有正文结构，推荐模板不会覆盖它。" : "请选择推荐模板，或创建学生自定义章节。"); }).catch((cause) => setNotice(cause instanceof Error ? cause.message : "无法加载结构规划器。")); }, [project?.id]);
  if (!project) return <ProjectRequiredState title="打开项目后规划论文结构" description="结构规划只保存到当前项目，不会生成示例正文。" />;
  if (!workspace) return <ViewShell><PageHeader eyebrow="写作与过程 / 论文大纲" title="论文结构规划器" description={notice} /></ViewShell>;
  const applyTemplate = async () => { if (workspace.sections.length) { setNotice("已有正文结构，不能套用模板覆盖；请使用学生自定义章节逐项补充。"); return; } const sections = templates.map(([title, purpose], index) => ({ ...makeSection(workspace, title, index), purpose })); const saved = await writingService.saveSections(workspace, sections, "student", "学生选择推荐模板"); setWorkspace(saved); setNotice("推荐模板已转为当前项目自己的章节节点，可继续编辑。"); };
  const addCustom = async () => { const title = customTitle.trim(); if (!title) return; const sections = [...workspace.sections, makeSection(workspace, title, workspace.sections.length)]; const saved = await writingService.saveSections(workspace, sections, "student", "新增学生自定义章节"); setWorkspace(saved); setCustomTitle(""); setNotice("学生自定义章节已保存。"); };
  const proposeOutline = async () => { const provider = getActiveBrowserProvider(); if (!provider) { setNotice("未配置可用 AI Provider；不会生成大纲提案。"); return; } setAiBusy(true); try { const response = await askConfiguredProvider(provider, `请为学生论文提出一个章节结构建议。只能依据以下已确认要求，不得推断学校硬规则；只返回 JSON 数组，每项包含 title、purpose：${JSON.stringify(requirements.requirements.map((item) => ({ key: item.requirementKey, label: item.label, description: item.description })))}。`); const parsed = JSON.parse(response) as Array<{ title?: string; purpose?: string }>; const titles = parsed.filter((item) => item.title?.trim()).map((item) => `${item.title!.trim()}｜${item.purpose?.trim() || "待由学生设定章节目标"}`); setAiProposal(titles.length ? titles : ["证据不足｜AI 未返回可验证的章节结构"]) } catch { setNotice("AI 大纲提案无法验证，未改变当前章节。"); } finally { setAiBusy(false); } };
  const acceptAiOutline = async () => { if (!aiProposal?.length || aiProposal[0].startsWith("证据不足")) return; const sections = aiProposal.map((item, index) => { const [title, purpose] = item.split("｜"); return { ...makeSection(workspace, title, index), purpose }; }); const saved = await writingService.saveSections(workspace, sections, "student", "学生接受 AI 大纲提案"); setWorkspace(saved); setAiProposal(null); setNotice("AI 大纲提案已由学生明确接受并保存；原有章节未被自动覆盖。"); };
  return <ViewShell><PageHeader eyebrow="写作与过程 / 论文大纲" title="论文结构规划器" description="硬性要求、系统推荐和学生自定义分层显示；结构变化不会覆盖已有正文。" /><div className="outline-planner-grid"><SectionCard title="输入来源分层" description="只有真实确认的要求才会显示为硬性要求。"><div className="planner-source-card confirmed"><ShieldCheck size={17} /><div><b>Confirmed Requirement · 硬性要求</b><span>{requirements.requirements.length ? `当前项目已确认 ${requirements.requirements.length} 条，可回到论文要求查看来源。` : "当前没有已确认的章节结构要求；系统不会推断学校规则。"}</span></div></div><div className="planner-source-card recommendation"><Sparkles size={17} /><div><b>System Recommendation · 推荐模板</b><span>本科论文常见结构，仅供学生选择，不代表学校规定。</span></div><button onClick={() => void applyTemplate()} disabled={workspace.sections.length > 0}>应用推荐模板</button></div><div className="planner-source-card student"><BookOpen size={17} /><div><b>Student-defined · 学生自定义</b><span>创建后成为本项目自己的稳定章节节点。</span></div></div><button onClick={() => void proposeOutline()} disabled={aiBusy}>{aiBusy ? "生成提案中…" : "生成 AI 大纲提案"}</button>{aiProposal && <div className="planner-ai-proposal"><b>待学生确认的提案</b>{aiProposal.map((item) => <p key={item}>{item}</p>)}<button onClick={() => void acceptAiOutline()} disabled={aiProposal[0].startsWith("证据不足")}>接受并保存</button><button onClick={() => setAiProposal(null)}>拒绝</button></div>}</SectionCard><SectionCard title="当前章节树" description={`${workspace.sections.length} 个章节 · ${notice}`}><div className="planner-section-list">{workspace.sections.length ? workspace.sections.map((section) => <article key={section.id}><CheckCircle2 size={15} /><div><b>{section.title}</b><span>{section.purpose || "尚未设置章节目标"} · {section.wordCount} 字</span></div><small>学生项目节点</small></article>) : <p className="planner-empty">暂无章节。推荐模板不会自动写入，需由学生明确选择。</p>}</div><div className="planner-add"><input value={customTitle} onChange={(event) => setCustomTitle(event.target.value)} placeholder="例如：稳健性检验" onKeyDown={(event) => { if (event.key === "Enter") void addCustom(); }} /><button onClick={() => void addCustom()}><Plus size={14} />添加自定义章节</button></div></SectionCard></div></ViewShell>;
}
