import { useEffect, useMemo, useRef, useState } from "react";
import { BookOpen, Check, FileDown, History, Plus, RotateCcw, Save, Search, Sparkles, X } from "lucide-react";
import { useProjectStore } from "@/stores/project-store";
import { useRequirementStore } from "@/stores/requirement-store";
import { literatureWorkspaceService } from "@/services/literatureWorkspaceService";
import type { WorkspaceRow } from "@/repositories/literatureWorkspaceRepository";
import { verifyDraftNumbers } from "@/services/evidenceGuardrails";
import type { EvidenceBlock } from "@/services/evidenceGuardrails";
import { writingService } from "@/services/writingService";
import { askConfiguredProvider, getActiveBrowserProvider } from "@/ai/providerClient";
import type { CitationAudit, ThesisAiProposal, ThesisSection, WritingWorkspace } from "@/types/writing";
import { errorMessage } from "@/lib/app-error";
import "./writing.css";

const stamp = () => new Date().toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit" });
const newSection = (documentId: string, projectId: string, order: number): ThesisSection => ({ id: crypto.randomUUID(), documentId, projectId, parentId: null, sortOrder: order, headingLevel: 1, title: `第 ${order + 1} 章`, content: "", contentFormat: "html", wordCount: 0, purpose: "", targetLength: null, sourcePlan: [], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() });

export function WritingPage() {
  const { projects, activeProjectId, loadProjects, error: projectError } = useProjectStore(); const requirements = useRequirementStore();
  const project = projects.find((item) => item.id === activeProjectId) ?? projects[0];
  const [workspace, setWorkspace] = useState<WritingWorkspace | null>(null); const [selectedId, setSelectedId] = useState<string | null>(null); const [rows, setRows] = useState<WorkspaceRow[]>([]); const [evidence, setEvidence] = useState<EvidenceBlock[]>([]); const [citationAudit, setCitationAudit] = useState<CitationAudit | null>(null); const [query, setQuery] = useState(""); const [message, setMessage] = useState("正在加载正文…"); const [error, setError] = useState<string | null>(null); const [proposal, setProposal] = useState<ThesisAiProposal | null>(null); const [aiRunning, setAiRunning] = useState(false); const saveTimer = useRef<number | undefined>(undefined);
  useEffect(() => { void loadProjects(); }, [loadProjects]);
  useEffect(() => { if (!project) return; let cancelled = false; setWorkspace(null); setError(null); setMessage("正在加载正文…"); void Promise.all([writingService.load(project.id, project.title), requirements.load(project.id), literatureWorkspaceService.list(project.id, "all").catch(() => []), writingService.listEvidence(project.id), writingService.auditCitations(project.id)]).then(([next, _requirements, literature, evidenceRows, audit]) => { if (cancelled) return; setWorkspace(next); setRows(literature); setEvidence(evidenceRows); setCitationAudit(audit); setSelectedId(next.sections[0]?.id ?? null); setMessage(next.sections.length ? `已恢复 · ${stamp()}` : "尚无章节，请从左侧创建"); }).catch((cause) => { if (!cancelled) setError(errorMessage(cause, "无法加载论文正文。")); }); return () => { cancelled = true; }; }, [project?.id]);
  const section = workspace?.sections.find((item) => item.id === selectedId) ?? workspace?.sections[0];
  const filteredRows = useMemo(() => rows.filter((row) => !query.trim() || `${row.title} ${row.authors} ${row.doi}`.toLowerCase().includes(query.toLowerCase())), [query, rows]);
  const updateSections = (nextSections: ThesisSection[], label = "自动保存") => { if (!workspace) return; setWorkspace({ ...workspace, sections: nextSections }); window.clearTimeout(saveTimer.current); saveTimer.current = window.setTimeout(() => { void writingService.saveSections(workspace, nextSections, "student", label).then((saved) => { setWorkspace(saved); setMessage(`已保存 · ${stamp()}`); }).catch((cause) => setError(cause instanceof Error ? cause.message : "保存失败，正文未确认写入。")); }, 650); };
  const addChapter = () => { if (!workspace) return; const next = [...workspace.sections, newSection(workspace.document.id, workspace.document.projectId, workspace.sections.length)]; setSelectedId(next.at(-1)?.id ?? null); updateSections(next, "新增章节"); };
  const editSection = (patch: Partial<ThesisSection>) => { if (!workspace || !section) return; updateSections(workspace.sections.map((item) => item.id === section.id ? { ...item, ...patch } : item)); };
  const insertCitation = async (row: WorkspaceRow) => { if (!workspace || !section) return; const citation = await writingService.saveCitation(workspace, { projectId: workspace.document.projectId, documentId: workspace.document.id, sectionId: section.id, literatureId: row.id, anchor: `cite-${crypto.randomUUID()}`, locator: null, prefix: "", suffix: "", renderText: `[${row.authors || row.title}, ${row.year ?? "n.d."}]` }); const linked = await writingService.saveSourceLink(citation, { projectId: workspace.document.projectId, documentId: workspace.document.id, sectionId: section.id, sourceType: "literature", sourceId: row.id, locator: null, label: row.title, status: "linked", snapshotText: citation.citations.at(-1)?.renderText ?? "" }); const updatedSection = { ...section, content: `${section.content}<p>${citation.citations.at(-1)?.renderText ?? ""}</p>` }; const saved = await writingService.saveSections(linked, linked.sections.map((item) => item.id === section.id ? updatedSection : item), "student", "插入结构化引用"); setWorkspace(saved); setMessage("已插入结构化引用 · 来源已绑定"); };
  const insertEvidence = async (item: EvidenceBlock) => { if (!workspace || !section) return; if (item.stale) { setError("该 evidence 已 stale，不能标记为当前已核验；请先刷新或保留快照。"); return; } const linked = await writingService.saveSourceLink(workspace, { projectId: workspace.document.projectId, documentId: workspace.document.id, sectionId: section.id, sourceType: "evidence", sourceId: item.id, locator: item.runId, label: item.title, status: "linked", snapshotText: item.metrics.map((metric) => `${metric.key}=${metric.value}`).join("; "), evidenceId: item.id, artifactId: item.artifactIds?.[0] ?? null, runId: item.runId }); const saved = await writingService.saveSections(linked, linked.sections.map((current) => current.id === section.id ? { ...current, content: `${current.content}<p>[实证证据：${item.title}]</p>` } : current), "student", "插入 evidence 引用"); setWorkspace(saved); setMessage("已绑定 Phase 7 evidence；上游变化会标记 stale"); };
  const createProposal = async () => { if (!workspace || !section || !section.content.trim()) { setMessage("请先选择有正文的章节，再生成改写提案。"); return; } const provider = getActiveBrowserProvider(); if (!provider) { setError("未配置可用 AI Provider。正文未改变；请在设置中配置并启用供应商。"); return; } setAiRunning(true); setError(null); try { const text = section.content.replace(/<[^>]+>/g, " ").trim(); const sectionLinks = workspace.links.filter((link) => link.sectionId === section.id); const sourceIds = [...new Set([...sectionLinks.map((link) => link.sourceId), ...workspace.citations.filter((citation) => citation.sectionId === section.id).map((citation) => citation.literatureId)])]; const selectedEvidence = evidence.filter((item) => sectionLinks.some((link) => link.sourceType === "evidence" && link.sourceId === item.id)); const response = await askConfiguredProvider(provider, `你是学生论文写作辅助工具。请只改写下面当前选区，不引入未提供的事实、数字、作者、DOI 或年份。若来源不足，请明确写“证据不足”，不要编造引用。只返回改写后的正文，不要覆盖原文。\n当前章节：${section.title}\n已选来源 ID：${sourceIds.length ? sourceIds.join(", ") : "无"}\n原文：${text}`); const numbers = response.match(/[-+]?\d+(?:\.\d+)?/g) ?? []; const originalNumbers = new Set(text.match(/[-+]?\d+(?:\.\d+)?/g) ?? []); const verified = selectedEvidence.length ? verifyDraftNumbers(response, selectedEvidence).missing : []; const unsupported = [...new Set(numbers.filter((value) => !originalNumbers.has(value) && !selectedEvidence.some((item) => item.metrics.some((metric) => String(metric.value) === value))).concat(verified))]; const next = await writingService.saveProposal(workspace, { projectId: workspace.document.projectId, documentId: workspace.document.id, sectionId: section.id, operation: "academicize", originalText: text, proposedText: response, usedSourceIds: sourceIds, unsupported, model: provider.model || provider.id, promptVersion: "phase8-v1", contextIds: [section.id, ...sourceIds], status: "pending" }); setWorkspace(next); setProposal(next.proposals[0]); } catch (cause) { setError(cause instanceof Error ? cause.message : "AI 提案生成失败，正文未改变。"); } finally { setAiRunning(false); } };
  const resolve = async (status: ThesisAiProposal["status"]) => { if (!workspace || !proposal || !section) return; const next = await writingService.resolveProposal(workspace, proposal.id, status); if (status === "accepted") { const saved = await writingService.saveSections(next, next.sections.map((item) => item.id === section.id ? { ...item, content: proposal.proposedText } : item), "ai", "接受 AI 提案"); setWorkspace(saved); } else setWorkspace(next); setProposal(null); setMessage(status === "accepted" ? "提案已接受并创建可追溯版本" : "提案已拒绝，正文未改变"); };
  const restore = async (revisionId: string) => { if (!workspace) return; const revision = workspace.revisions.find((item) => item.id === revisionId); if (!revision) return; const saved = await writingService.saveSections(workspace, revision.snapshot, "restore", `恢复 v${revision.versionNumber}`); setWorkspace(saved); setSelectedId(revision.snapshot[0]?.id ?? null); setMessage(`已恢复 v${revision.versionNumber}，历史版本仍保留`); };
  const exportDocx = async () => { if (!workspace) return; try { const stable = workspace.revisions.length ? workspace : await writingService.saveSections(workspace, workspace.sections, "student", "导出前快照"); if (stable !== workspace) setWorkspace(stable); const referencedIds = new Set(stable.citations.map((citation) => citation.literatureId)); const bibliography = rows.filter((row) => referencedIds.has(row.id)).map((row) => ({ title: row.title, authors: row.authors, year: row.year })); const blob = await writingService.exportDocx(stable, bibliography); const bytes = new Uint8Array(await blob.arrayBuffer()); const fileHash = Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", bytes))).map((x) => x.toString(16).padStart(2, "0")).join(""); const filename = `${stable.document.title || "thesis"}-v${stable.document.activeVersion}.docx`; const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); await writingService.recordExport(stable, filename, fileHash, [], ["目录/页码字段需在 Word 中更新", "confirmed requirement 的未识别格式需手工检查"]); setMessage("DOCX snapshot 已生成并记录 manifest；正文仍以结构化数据为事实源"); } catch (cause) { setError(cause instanceof Error ? cause.message : "DOCX 导出失败，未生成假成功提示。"); } };
  if (projectError) return <div className="writing-empty-state" role="alert"><h2>项目读取失败</h2><p>{projectError.message}</p></div>;
  if (!project) return <div className="writing-empty-state"><BookOpen size={22} /><h2>请先打开项目</h2><p>正文写作只使用当前项目的真实数据。</p></div>;
  if (error) return <div className="writing-empty-state"><h2>正文加载失败</h2><p>{error}</p><button onClick={() => location.reload()}>重试</button></div>;
  if (!workspace) return <div className="writing-empty-state" role="status" aria-label="正在加载真实项目数据…"><BookOpen size={22} /><p>正在加载真实项目数据…</p></div>;
  return <div className="writing-page phase8-writing"><span className="phase8-compat-label">关联文件</span>
    <aside className="write-outline"><header><strong>论文结构</strong><button className="add-chapter" onClick={addChapter}><Plus size={13} /> 新章节</button></header><div className="outline-source-badges"><span>Confirmed 要求 {requirements.requirements.length}</span><span>学生自定义章节</span></div><div className="outline-scroll">{workspace?.sections.length ? workspace.sections.map((item) => <button className={`outline-item ${item.id === section?.id ? "active" : ""}`} key={item.id} onClick={() => setSelectedId(item.id)}><span>{item.title}</span><small>{item.wordCount} 字</small></button>) : <div className="outline-empty"><BookOpen size={18} /><span>还没有章节</span><button onClick={addChapter}>创建第一章</button></div>}</div><div className="outline-progress"><div><span>正文进度</span><b>{workspace?.sections.reduce((n, item) => n + item.wordCount, 0) ?? 0} 字</b></div><p>保存来源：正式正文版本</p></div></aside>
    <main className="write-workbench"><header className="writer-commandbar"><div className="breadcrumbs"><b>{workspace.document.title}</b><span>· {section?.title ?? "未选择章节"}</span><span className="autosave"><Save size={12} /> {message}</span></div><div className="writer-actions"><button onClick={() => setMessage(`当前版本 v${workspace.document.activeVersion}`)}><History size={14} />版本 v{workspace.document.activeVersion}</button><button className="ai-action" disabled={aiRunning || !section} onClick={() => void createProposal()}><Sparkles size={14} />{aiRunning ? "生成中…" : "生成 AI 提案"}</button></div></header><div className="writing-format-note">正文是学生资产 · AI 结果进入提案区，只有“接受”才会写入 · 无来源内容不会标记为已核验</div>{section ? <><div className="section-title-row"><input value={section.title} onChange={(event) => editSection({ title: event.target.value })} aria-label="章节标题" /><span>{section.wordCount} 字 · {section.content.length} 字符</span></div><div className="editor-toolbar"><button onClick={() => editSection({ content: `${section.content}<strong>重点</strong>` })}>加粗</button><button onClick={() => editSection({ content: `${section.content}<em>强调</em>` })}>斜体</button><span className="toolbar-hint">支持稳定 HTML 段落格式</span></div><div className="editor-scroller"><article className="paper-editor" contentEditable suppressContentEditableWarning onInput={(event) => editSection({ content: event.currentTarget.innerHTML })} dangerouslySetInnerHTML={{ __html: section.content || "<p><br></p>" }} /></div><footer className="editor-footer"><span>● {message}</span><i /> <span>{workspace.citations.length} 条结构化引用</span></footer></> : <div className="writing-empty-state"><BookOpen size={22} /><h2>尚无正文写作相关真实记录</h2><p>尚无章节，创建后才会出现正式编辑区。</p><button onClick={addChapter}>创建章节</button></div>}</main>
    <aside className="write-ai phase8-sidebar"><header><div><Sparkles size={15} /> 研究证据侧栏</div><span>仅当前项目</span></header><div className="material-search"><Search size={14} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="检索文献题录" /></div><section className="source-panel"><h3>真实文献 <small>{filteredRows.length}</small></h3>{filteredRows.slice(0, 8).map((row) => <article key={row.id}><div><b>{row.title}</b><span>{row.authors || "作者待补充"} · {row.year ?? "年份待补充"}</span></div><button onClick={() => void insertCitation(row)} disabled={!section}>插入引用</button></article>)}{!filteredRows.length && <p className="source-empty">暂无文献记录。请先导入或手工确认真实文献。</p>}</section><section className="source-panel evidence-panel"><h3>Phase 7 evidence <small>{evidence.length}</small></h3>{evidence.slice(0, 5).map((item) => <article key={item.id}><div><b>{item.title}</b><span>{item.stale ? "stale · 需刷新或保留快照" : `${item.metrics.length} 个可核验指标`}</span></div><button onClick={() => void insertEvidence(item)} disabled={!section || item.stale}>绑定</button></article>)}{!evidence.length && <p className="source-empty">暂无当前项目 evidence。先完成真实分析运行。</p>}</section><section className="proposal-panel"><h3>AI 提案 {proposal ? <small>待处理</small> : null}</h3>{proposal ? <><div className="diff-box"><del>{proposal.originalText.slice(0, 180)}</del><ins>{proposal.proposedText.slice(0, 220)}</ins></div><p>used source ids：{proposal.usedSourceIds.length ? proposal.usedSourceIds.join(", ") : "无（证据不足）"}{proposal.unsupported.length ? ` · unsupported 数值：${proposal.unsupported.join(", ")}` : ""}</p><div className="proposal-actions"><button onClick={() => void resolve("accepted")} disabled={proposal.unsupported.length > 0}><Check size={14} />接受</button><button onClick={() => void resolve("rejected")}><X size={14} />拒绝</button></div></> : <p className="source-empty">选中章节后生成提案。结果不会自动覆盖正文。</p>}</section><section className="history-panel"><h3>历史版本 <small>{workspace.revisions.length}</small></h3>{workspace.revisions.slice(0, 5).map((revision) => <article key={revision.id}><span>v{revision.versionNumber} · {revision.source === "ai" ? "AI" : revision.source === "restore" ? "恢复" : "学生"}</span><button onClick={() => void restore(revision.id)} title="恢复此版本"><RotateCcw size={13} /></button></article>)}</section><div className="export-panel"><button onClick={() => void exportDocx()}><FileDown size={14} />导出 DOCX snapshot</button></div></aside>
  </div>;
}
